/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Home;

import Connect_DB.CheckOracleConnection;
import Process.Ve;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DUNG
 */
public class Thanh_ToanDatVe extends javax.swing.JFrame {

    /**
     * Creates new form SuaDatVe
     */
    public Thanh_ToanDatVe() {
        initComponents();
        ComboboxIDdve();
        fillTable();
    }

    public void CloseFrame() {
        super.dispose();
    }
        Connection conn;
        PreparedStatement pst;

    public void ComboboxIDdve() {
        try {
            Connection conn = CheckOracleConnection.getMyConnection();
            String sql = "SELECT ID_DATVE FROM DATVE";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                IDDve.addItem(rs.getString(1));
            }
            rs.close();
            pstmt.close();
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(Them_GiaVe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Them_GiaVe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A = new javax.swing.JPanel();
        Logo2 = new javax.swing.JLabel();
        Home2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        QL_GiaVe = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        DangXuat = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        QL_GiaVe2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        QL_GiaVe6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        B = new javax.swing.JPanel();
        Sửa = new javax.swing.JPanel();
        trolai = new javax.swing.JButton();
        thanhtoan = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        IDDve = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhsachdatve = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        A.setBackground(new java.awt.Color(205, 247, 247));
        A.setPreferredSize(new java.awt.Dimension(220, 500));

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/HÃNG XE KHÁCH (200 × 200 px).png"))); // NOI18N
        Logo2.setToolTipText("");

        Home2.setBackground(new java.awt.Color(251, 250, 238));
        Home2.setPreferredSize(new java.awt.Dimension(200, 20));
        Home2.setRequestFocusEnabled(false);

        jLabel8.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel8.setText("        Trang chủ");

        javax.swing.GroupLayout Home2Layout = new javax.swing.GroupLayout(Home2);
        Home2.setLayout(Home2Layout);
        Home2Layout.setHorizontalGroup(
            Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Home2Layout.setVerticalGroup(
            Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        QL_GiaVe.setBackground(new java.awt.Color(251, 250, 238));
        QL_GiaVe.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel20.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel20.setText("        Quản lý vé");

        javax.swing.GroupLayout QL_GiaVeLayout = new javax.swing.GroupLayout(QL_GiaVe);
        QL_GiaVe.setLayout(QL_GiaVeLayout);
        QL_GiaVeLayout.setHorizontalGroup(
            QL_GiaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_GiaVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QL_GiaVeLayout.setVerticalGroup(
            QL_GiaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        DangXuat.setBackground(new java.awt.Color(251, 250, 238));
        DangXuat.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel21.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel21.setText("        Đăng xuất");

        javax.swing.GroupLayout DangXuatLayout = new javax.swing.GroupLayout(DangXuat);
        DangXuat.setLayout(DangXuatLayout);
        DangXuatLayout.setHorizontalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DangXuatLayout.setVerticalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        QL_GiaVe2.setBackground(new java.awt.Color(251, 250, 238));
        QL_GiaVe2.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel22.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel22.setText("        Quản lý hành khách");

        javax.swing.GroupLayout QL_GiaVe2Layout = new javax.swing.GroupLayout(QL_GiaVe2);
        QL_GiaVe2.setLayout(QL_GiaVe2Layout);
        QL_GiaVe2Layout.setHorizontalGroup(
            QL_GiaVe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_GiaVe2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QL_GiaVe2Layout.setVerticalGroup(
            QL_GiaVe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        QL_GiaVe6.setBackground(new java.awt.Color(251, 250, 238));
        QL_GiaVe6.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel25.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel25.setText("        Quản lý hoàn vé");

        javax.swing.GroupLayout QL_GiaVe6Layout = new javax.swing.GroupLayout(QL_GiaVe6);
        QL_GiaVe6.setLayout(QL_GiaVe6Layout);
        QL_GiaVe6Layout.setHorizontalGroup(
            QL_GiaVe6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_GiaVe6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QL_GiaVe6Layout.setVerticalGroup(
            QL_GiaVe6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ALayout = new javax.swing.GroupLayout(A);
        A.setLayout(ALayout);
        ALayout.setHorizontalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(QL_GiaVe6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QL_GiaVe2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QL_GiaVe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        ALayout.setVerticalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALayout.createSequentialGroup()
                .addComponent(Logo2)
                .addGap(18, 18, 18)
                .addComponent(Home2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QL_GiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QL_GiaVe6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QL_GiaVe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        B.setBackground(new java.awt.Color(251, 250, 238));
        B.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Sửa.setOpaque(false);
        Sửa.setPreferredSize(new java.awt.Dimension(210, 35));

        trolai.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        trolai.setText("Trở lại");
        trolai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trolaiActionPerformed(evt);
            }
        });

        thanhtoan.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        thanhtoan.setText("Thanh toán");
        thanhtoan.setPreferredSize(new java.awt.Dimension(107, 30));
        thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhtoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SửaLayout = new javax.swing.GroupLayout(Sửa);
        Sửa.setLayout(SửaLayout);
        SửaLayout.setHorizontalGroup(
            SửaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SửaLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(trolai)
                .addGap(38, 38, 38))
        );
        SửaLayout.setVerticalGroup(
            SửaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SửaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(trolai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSeparator1.setForeground(new java.awt.Color(205, 247, 247));

        jLabel16.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel16.setText("Chào mừng đến với sửa đặt vé!");

        jSeparator2.setForeground(new java.awt.Color(205, 247, 247));

        IDDve.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lora", 0, 14)); // NOI18N
        jLabel1.setText("ID Đặt vé");

        jLabel59.setFont(new java.awt.Font("Lora", 2, 14)); // NOI18N
        jLabel59.setText("Sự hài lòng của quý khách");

        jLabel23.setFont(new java.awt.Font("Lora", 2, 14)); // NOI18N
        jLabel23.setText("là minh chứng cho chất lượng dịch vụ của hãng xe Thanh Xuân");

        danhsachdatve.setAutoCreateRowSorter(true);
        danhsachdatve.setBackground(new java.awt.Color(251, 250, 238));
        danhsachdatve.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        danhsachdatve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Đặt vé", "ID_Hành khách", "ID_Vé", "ID_Nhân viên", "Ngày thêm", "Tổng tiền", "Tình trạng"
            }
        ));
        danhsachdatve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                danhsachdatveMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(danhsachdatve);

        javax.swing.GroupLayout BLayout = new javax.swing.GroupLayout(B);
        B.setLayout(BLayout);
        BLayout.setHorizontalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(IDDve, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(BLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 499, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(BLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel59)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sửa, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(BLayout.createSequentialGroup()
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel23))
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BLayout.setVerticalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDDve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addComponent(Sửa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trolaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trolaiActionPerformed
        // TODO add your handling code here:
        QuanLyDatVe quanlydatve = new QuanLyDatVe();
        quanlydatve.setVisible(true);
        CloseFrame();

    }//GEN-LAST:event_trolaiActionPerformed

    private void thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhtoanActionPerformed
        // TODO add your handling code here:
        int iddve = Integer.valueOf((String) IDDve.getSelectedItem());
        Ve thanhtoandatve = new Ve();
        int z = 0;
        z = thanhtoandatve.ThanhToanDatVe(iddve);
        if (z > 0) {
            JOptionPane.showMessageDialog(this, "Sửa thành công!", "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE, null);
                            DefaultTableModel model = (DefaultTableModel) danhsachdatve.getModel();
                model.setRowCount(0);
                fillTable();

        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }

    }//GEN-LAST:event_thanhtoanActionPerformed

    private void danhsachdatveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_danhsachdatveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_danhsachdatveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thanh_ToanDatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thanh_ToanDatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thanh_ToanDatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thanh_ToanDatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thanh_ToanDatVe().setVisible(true);
            }
        });
    }

    public void fillTable() {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##DB_XEKHACHTHANHXUAN", "userpass");
            java.sql.Statement st = conn.createStatement();
            String sql = "SELECT ID_DATVE, ID_HANHKHACH, ID_VE, ID_NHANVIEN, NGAYTHEM, TONGTIEN, TINHTRANG FROM DATVE";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                String iddv = rs.getString("ID_DATVE");
                String idhk = rs.getString("ID_HANHKHACH");
                String idv = rs.getString("ID_VE");
                String idnv = rs.getString("ID_NHANVIEN");
                String ngaythem = String.valueOf(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(rs.getTimestamp("NGAYTHEM")));
                String tongtien = rs.getString("TONGTIEN");
                String tt = rs.getString("TINHTRANG");
                String tbData[] = {iddv, idhk, idv, idnv, ngaythem, tongtien, tt};
                DefaultTableModel tblModel = (DefaultTableModel) danhsachdatve.getModel();

                tblModel.addRow(tbData);
            }

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A;
    private javax.swing.JPanel B;
    private javax.swing.JPanel DangXuat;
    private javax.swing.JPanel Home2;
    private javax.swing.JComboBox<String> IDDve;
    private javax.swing.JLabel Logo2;
    private javax.swing.JPanel QL_GiaVe;
    private javax.swing.JPanel QL_GiaVe2;
    private javax.swing.JPanel QL_GiaVe6;
    private javax.swing.JPanel Sửa;
    private javax.swing.JTable danhsachdatve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton thanhtoan;
    private javax.swing.JButton trolai;
    // End of variables declaration//GEN-END:variables
}
