/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Home;

import Connect_DB.CheckOracleConnection;
import Process.Ve;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DUNG
 */
public class Them_GiaVe extends javax.swing.JFrame {
//        private JComboBox IDloaixe;

    /**
     * Creates new form ThemGiaVe
     */
    public Them_GiaVe() {
        initComponents();
        ComboboxIDtuyen();
        ComboboxIDloai();
        fillTable();

    }

    public void CloseFrame() {
        super.dispose();
    }
    Connection conn;
    PreparedStatement pst;

    public void ComboboxIDtuyen() {
        try {
            Connection conn = CheckOracleConnection.getMyConnection();
            String sql = "SELECT ID_TUYENXE FROM TUYENXE";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                IDtuyenxe.addItem(rs.getString(1));
            }
            rs.close();
            pstmt.close();
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(Them_GiaVe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Them_GiaVe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    public void ComboboxIDloai() {
        try {
            Connection conn = CheckOracleConnection.getMyConnection();
            String sql = "SELECT ID_LOAIXE FROM LOAIXE";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                IDloaixe.addItem(rs.getString("ID_LOAIXE"));

            }
            rs.close();
            pstmt.close();
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(Them_GiaVe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Them_GiaVe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel54 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IDtuyenxe = new javax.swing.JComboBox<>();
        GiaVe = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        IDloaixe = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        danhsachgiave = new javax.swing.JTable();
        jLabel59 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Them = new javax.swing.JButton();
        trolai = new javax.swing.JButton();
        A = new javax.swing.JPanel();
        Logo2 = new javax.swing.JLabel();
        Home2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        QL_GiaVe = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        DangXuat = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        QL_GiaVe2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        QL_GiaVe6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B.setBackground(new java.awt.Color(251, 250, 238));
        B.setPreferredSize(new java.awt.Dimension(680, 500));

        jSeparator1.setForeground(new java.awt.Color(205, 247, 247));

        jLabel54.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel54.setText("Mời thêm giá vé!");

        jPanel7.setBackground(new java.awt.Color(251, 250, 238));

        jSeparator3.setForeground(new java.awt.Color(205, 247, 247));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(665, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(97, 97, 97))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        jPanel2.setBackground(new java.awt.Color(251, 250, 238));

        jLabel2.setFont(new java.awt.Font("Lora", 0, 14)); // NOI18N
        jLabel2.setText("ID Loại xe");

        jLabel3.setFont(new java.awt.Font("Lora", 0, 14)); // NOI18N
        jLabel3.setText("ID Tuyến xe");

        IDtuyenxe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        IDtuyenxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtuyenxeActionPerformed(evt);
            }
        });

        GiaVe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        GiaVe.setToolTipText("Giá vé"); // NOI18N
        GiaVe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));
        GiaVe.setMinimumSize(new java.awt.Dimension(64, 25));
        GiaVe.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel1.setFont(new java.awt.Font("Lora", 0, 14)); // NOI18N
        jLabel1.setText("Giá vé");

        IDloaixe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDloaixeMouseClicked(evt);
            }
        });
        IDloaixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDloaixeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(58, 99, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(65, 65, 65))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(GiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(IDtuyenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IDloaixe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(149, 149, 149))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IDloaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDtuyenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7))
        );

        danhsachgiave.setBackground(new java.awt.Color(251, 250, 238));
        danhsachgiave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));
        danhsachgiave.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        danhsachgiave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID loại xe", "ID tuyến xe", "Giá vé"
            }
        ));
        danhsachgiave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                danhsachgiaveMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(danhsachgiave);

        jLabel59.setFont(new java.awt.Font("Lora", 2, 14)); // NOI18N
        jLabel59.setText("Sự hài lòng của quý khách");

        jLabel22.setFont(new java.awt.Font("Lora", 2, 14)); // NOI18N
        jLabel22.setText("là minh chứng cho chất lượng dịch vụ của hãng xe Thanh Xuân");

        Them.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        Them.setText("Thêm");
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        trolai.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        trolai.setText("Trở lại");
        trolai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trolaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BLayout = new javax.swing.GroupLayout(B);
        B.setLayout(BLayout);
        BLayout.setHorizontalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BLayout.createSequentialGroup()
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel54))
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(Them)
                        .addGap(195, 195, 195)
                        .addComponent(trolai)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BLayout.createSequentialGroup()
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel22))
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel59)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BLayout.setVerticalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trolai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(6, 6, 6))
        );

        A.setBackground(new java.awt.Color(205, 247, 247));
        A.setPreferredSize(new java.awt.Dimension(220, 500));

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/HÃNG XE KHÁCH (200 × 200 px).png"))); // NOI18N
        Logo2.setToolTipText("");

        Home2.setBackground(new java.awt.Color(251, 250, 238));
        Home2.setPreferredSize(new java.awt.Dimension(200, 20));
        Home2.setRequestFocusEnabled(false);

        jLabel8.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel8.setText("        Trang chủ");

        javax.swing.GroupLayout Home2Layout = new javax.swing.GroupLayout(Home2);
        Home2.setLayout(Home2Layout);
        Home2Layout.setHorizontalGroup(
            Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Home2Layout.setVerticalGroup(
            Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        QL_GiaVe.setBackground(new java.awt.Color(251, 250, 238));
        QL_GiaVe.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel19.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel19.setText("        Quản lý vé");

        javax.swing.GroupLayout QL_GiaVeLayout = new javax.swing.GroupLayout(QL_GiaVe);
        QL_GiaVe.setLayout(QL_GiaVeLayout);
        QL_GiaVeLayout.setHorizontalGroup(
            QL_GiaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_GiaVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QL_GiaVeLayout.setVerticalGroup(
            QL_GiaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        DangXuat.setBackground(new java.awt.Color(251, 250, 238));
        DangXuat.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel20.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel20.setText("        Đăng xuất");

        javax.swing.GroupLayout DangXuatLayout = new javax.swing.GroupLayout(DangXuat);
        DangXuat.setLayout(DangXuatLayout);
        DangXuatLayout.setHorizontalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DangXuatLayout.setVerticalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        QL_GiaVe2.setBackground(new java.awt.Color(251, 250, 238));
        QL_GiaVe2.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel21.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel21.setText("        Quản lý hành khách");

        javax.swing.GroupLayout QL_GiaVe2Layout = new javax.swing.GroupLayout(QL_GiaVe2);
        QL_GiaVe2.setLayout(QL_GiaVe2Layout);
        QL_GiaVe2Layout.setHorizontalGroup(
            QL_GiaVe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_GiaVe2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QL_GiaVe2Layout.setVerticalGroup(
            QL_GiaVe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        QL_GiaVe6.setBackground(new java.awt.Color(251, 250, 238));
        QL_GiaVe6.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel25.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel25.setText("        Quản lý hoàn vé");

        javax.swing.GroupLayout QL_GiaVe6Layout = new javax.swing.GroupLayout(QL_GiaVe6);
        QL_GiaVe6.setLayout(QL_GiaVe6Layout);
        QL_GiaVe6Layout.setHorizontalGroup(
            QL_GiaVe6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_GiaVe6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QL_GiaVe6Layout.setVerticalGroup(
            QL_GiaVe6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ALayout = new javax.swing.GroupLayout(A);
        A.setLayout(ALayout);
        ALayout.setHorizontalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(QL_GiaVe6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QL_GiaVe2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QL_GiaVe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        ALayout.setVerticalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALayout.createSequentialGroup()
                .addComponent(Logo2)
                .addGap(18, 18, 18)
                .addComponent(Home2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QL_GiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QL_GiaVe6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QL_GiaVe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(A, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addComponent(B, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
//        // TODO add your handling code here:
        int count = 1;
        String giave = GiaVe.getText();
        int idloaixe = Integer.valueOf((String) IDloaixe.getSelectedItem());
        int idtuyenxe = Integer.valueOf((String) IDtuyenxe.getSelectedItem());
        boolean flag = true;
        if (giave.equals("")) {

            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá vé\n");
            flag = false;
        }
        if (flag == true) {
            {
                String giavePattern = "\\d{1,50}";
                boolean flag3 = giave.matches(giavePattern);
                if (flag3 == false) {
                    JOptionPane.showMessageDialog(this, "Giá vé không hợp lệ");
                    flag = false;
                }
            }
        }
        if (flag == true) {
            Ve add_gia_ve = new Ve();
            int z = 0;
            z = add_gia_ve.ThemGiaVe(idloaixe, idtuyenxe, giave);
            if (z > 0) {
                JOptionPane.showMessageDialog(this, "  thành công!", "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE, null);
                DefaultTableModel model = (DefaultTableModel) danhsachgiave.getModel();
                model.setRowCount(0);
                fillTable();
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }


    }//GEN-LAST:event_ThemActionPerformed

    private void IDloaixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDloaixeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_IDloaixeActionPerformed

    private void IDtuyenxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtuyenxeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_IDtuyenxeActionPerformed

    private void IDloaixeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDloaixeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_IDloaixeMouseClicked

    private void danhsachgiaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_danhsachgiaveMouseClicked
    }//GEN-LAST:event_danhsachgiaveMouseClicked

    private void trolaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trolaiActionPerformed
        // TODO add your handling code here:
        QuanLyGiaVe quanlygiave = new QuanLyGiaVe();
        quanlygiave.setVisible(true);
        CloseFrame();

    }//GEN-LAST:event_trolaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Them_GiaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Them_GiaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Them_GiaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Them_GiaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Them_GiaVe().setVisible(true);
            }
        });
    }

    public void fillTable() {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##DB_XEKHACHTHANHXUAN", "userpass");
            java.sql.Statement st = conn.createStatement();
            String sql = "SELECT ID_LOAIXE, ID_TUYENXE, GIAVE FROM GIAVE";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                String idlx = rs.getString("ID_LOAIXE");
                String idtx = rs.getString("ID_TUYENXE");
                String gia = rs.getString("GIAVE");
                String tbData[] = {idlx, idtx, gia};
                DefaultTableModel tblModel = (DefaultTableModel) danhsachgiave.getModel();

                tblModel.addRow(tbData);
            }

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A;
    private javax.swing.JPanel B;
    private javax.swing.JPanel DangXuat;
    private javax.swing.JTextField GiaVe;
    private javax.swing.JPanel Home2;
    private javax.swing.JComboBox<String> IDloaixe;
    private javax.swing.JComboBox<String> IDtuyenxe;
    private javax.swing.JLabel Logo2;
    private javax.swing.JPanel QL_GiaVe;
    private javax.swing.JPanel QL_GiaVe2;
    private javax.swing.JPanel QL_GiaVe6;
    private javax.swing.JButton Them;
    private javax.swing.JTable danhsachgiave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton trolai;
    // End of variables declaration//GEN-END:variables
}
