/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Home;

import Connect_DB.CheckOracleConnection;
import Process.Ve;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DUNG
 */
public class Them_HoanVe extends javax.swing.JFrame {

    /**
     * Creates new form ThemHoanVe
     */
    public Them_HoanVe() {
        initComponents();
        ComboboxIDnhanvien();
//        ComboboxIDDatve();
        Ve.setVisible(false);
        Them.setVisible(false);
    }

    public void CloseFrame() {
        super.dispose();
    }
    Connection conn;
    PreparedStatement pst;

    public void ComboboxIDnhanvien() {
        try {
            Connection conn = CheckOracleConnection.getMyConnection();
            String sql = "SELECT ID_NHANVIEN FROM NHANVIEN";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                IDnv.addItem(rs.getString("ID_NHANVIEN"));
            }
            rs.close();
            pstmt.close();
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(Them_GiaVe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Them_GiaVe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A = new javax.swing.JPanel();
        Logo2 = new javax.swing.JLabel();
        Home2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        QL_GiaVe = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        DangXuat = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        QL_GiaVe2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        QL_GiaVe6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        B = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel54 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        Them = new javax.swing.JButton();
        trolai = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        IDNhanVien = new javax.swing.JLabel();
        IDDve = new javax.swing.JLabel();
        IDnv = new javax.swing.JComboBox<>();
        TimKiem = new javax.swing.JButton();
        IDDatve = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Ve = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        tuyenxe = new javax.swing.JLabel();
        diemlenxe = new javax.swing.JLabel();
        diemxuongxe = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        biensoxe = new javax.swing.JLabel();
        thoigiankhoihanh = new javax.swing.JLabel();
        thoigianden = new javax.swing.JLabel();
        giave = new javax.swing.JLabel();
        loaixe = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hoten1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        maveform = new javax.swing.JLabel();
        sdt = new javax.swing.JLabel();
        hoten2 = new javax.swing.JLabel();
        cmnd = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        vitrighe = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        email2 = new javax.swing.JLabel();
        email3 = new javax.swing.JLabel();
        email4 = new javax.swing.JLabel();
        email5 = new javax.swing.JLabel();
        email6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        A.setBackground(new java.awt.Color(205, 247, 247));
        A.setPreferredSize(new java.awt.Dimension(220, 500));

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/HÃNG XE KHÁCH (200 × 200 px).png"))); // NOI18N
        Logo2.setToolTipText("");

        Home2.setBackground(new java.awt.Color(251, 250, 238));
        Home2.setPreferredSize(new java.awt.Dimension(200, 20));
        Home2.setRequestFocusEnabled(false);

        jLabel8.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_home_page_20px_1.png"))); // NOI18N
        jLabel8.setText("        Trang chủ");

        javax.swing.GroupLayout Home2Layout = new javax.swing.GroupLayout(Home2);
        Home2.setLayout(Home2Layout);
        Home2Layout.setHorizontalGroup(
            Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Home2Layout.setVerticalGroup(
            Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        QL_GiaVe.setBackground(new java.awt.Color(251, 250, 238));
        QL_GiaVe.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel19.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel19.setText("        Quản lý vé");

        javax.swing.GroupLayout QL_GiaVeLayout = new javax.swing.GroupLayout(QL_GiaVe);
        QL_GiaVe.setLayout(QL_GiaVeLayout);
        QL_GiaVeLayout.setHorizontalGroup(
            QL_GiaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_GiaVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QL_GiaVeLayout.setVerticalGroup(
            QL_GiaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        DangXuat.setBackground(new java.awt.Color(251, 250, 238));
        DangXuat.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel20.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel20.setText("        Đăng xuất");

        javax.swing.GroupLayout DangXuatLayout = new javax.swing.GroupLayout(DangXuat);
        DangXuat.setLayout(DangXuatLayout);
        DangXuatLayout.setHorizontalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DangXuatLayout.setVerticalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        QL_GiaVe2.setBackground(new java.awt.Color(251, 250, 238));
        QL_GiaVe2.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel21.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel21.setText("        Quản lý hành khách");

        javax.swing.GroupLayout QL_GiaVe2Layout = new javax.swing.GroupLayout(QL_GiaVe2);
        QL_GiaVe2.setLayout(QL_GiaVe2Layout);
        QL_GiaVe2Layout.setHorizontalGroup(
            QL_GiaVe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_GiaVe2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QL_GiaVe2Layout.setVerticalGroup(
            QL_GiaVe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        QL_GiaVe6.setBackground(new java.awt.Color(251, 250, 238));
        QL_GiaVe6.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel25.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel25.setText("        Quản lý hoàn vé");

        javax.swing.GroupLayout QL_GiaVe6Layout = new javax.swing.GroupLayout(QL_GiaVe6);
        QL_GiaVe6.setLayout(QL_GiaVe6Layout);
        QL_GiaVe6Layout.setHorizontalGroup(
            QL_GiaVe6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_GiaVe6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QL_GiaVe6Layout.setVerticalGroup(
            QL_GiaVe6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ALayout = new javax.swing.GroupLayout(A);
        A.setLayout(ALayout);
        ALayout.setHorizontalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(QL_GiaVe6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QL_GiaVe2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QL_GiaVe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        ALayout.setVerticalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALayout.createSequentialGroup()
                .addComponent(Logo2)
                .addGap(18, 18, 18)
                .addComponent(Home2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QL_GiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QL_GiaVe6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QL_GiaVe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        B.setBackground(new java.awt.Color(251, 250, 238));
        B.setPreferredSize(new java.awt.Dimension(680, 500));

        jSeparator1.setForeground(new java.awt.Color(205, 247, 247));

        jLabel54.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel54.setText("Mời thêm hoàn vé!");

        jPanel7.setBackground(new java.awt.Color(251, 250, 238));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 151, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(288, 288, 288))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(58, 58, 58))
        );

        Them.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        Them.setText("Thêm");
        Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThemMouseClicked(evt);
            }
        });
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        trolai.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        trolai.setText("Trở lại");
        trolai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trolaiActionPerformed(evt);
            }
        });

        jLabel59.setFont(new java.awt.Font("Lora", 2, 14)); // NOI18N
        jLabel59.setText("Sự hài lòng của quý khách");

        jLabel22.setFont(new java.awt.Font("Lora", 2, 14)); // NOI18N
        jLabel22.setText("là minh chứng cho chất lượng dịch vụ của hãng xe Thanh Xuân");

        IDNhanVien.setFont(new java.awt.Font("Lora", 0, 14)); // NOI18N
        IDNhanVien.setText("ID nhân viên ");

        IDDve.setFont(new java.awt.Font("Lora", 0, 14)); // NOI18N
        IDDve.setText("ID đặt vé");

        IDnv.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        IDnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDnvActionPerformed(evt);
            }
        });

        TimKiem.setText("Tìm kiếm");
        TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemActionPerformed(evt);
            }
        });

        IDDatve.setPreferredSize(new java.awt.Dimension(64, 23));

        jSeparator4.setForeground(new java.awt.Color(205, 247, 247));

        javax.swing.GroupLayout BLayout = new javax.swing.GroupLayout(B);
        B.setLayout(BLayout);
        BLayout.setHorizontalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BLayout.createSequentialGroup()
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel54))
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BLayout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addGap(120, 120, 120))
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1)
                .addGap(82, 82, 82))
            .addGroup(BLayout.createSequentialGroup()
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IDNhanVien)
                            .addComponent(IDDve)
                            .addComponent(Them))
                        .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BLayout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(trolai))
                            .addGroup(BLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IDDatve, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDnv, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BLayout.setVerticalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel54)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDDve, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDDatve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BLayout.createSequentialGroup()
                        .addComponent(TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trolai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(15, 15, 15))
        );

        Ve.setBackground(new java.awt.Color(205, 247, 247));
        Ve.setPreferredSize(new java.awt.Dimension(500, 390));

        jLabel35.setFont(new java.awt.Font("Lora Medium", 1, 14)); // NOI18N
        jLabel35.setText("Hãng xe khách Thanh Xuân");

        jLabel41.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel41.setText("Tuyến xe:");

        jLabel42.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel42.setText("Điểm lên xe:");

        jLabel43.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel43.setText("Điểm xuống xe:");

        jLabel44.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel44.setText("Biển số xe:");

        jLabel45.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel45.setText("Thời gian khởi hành:");

        jLabel46.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel46.setText("Thời gian đến:");

        tuyenxe.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        tuyenxe.setText("jLabel27");

        diemlenxe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        diemlenxe.setText("jLabel27");

        diemxuongxe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        diemxuongxe.setText("jLabel27");

        jLabel47.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel47.setText("Giá vé: ");

        jLabel48.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel48.setText("Loại xe:");

        biensoxe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        biensoxe.setText("jLabel27");

        thoigiankhoihanh.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        thoigiankhoihanh.setText("jLabel27");

        thoigianden.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        thoigianden.setText("jLabel27");

        giave.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        giave.setText("jLabel27");

        loaixe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        loaixe.setText("jLabel27");

        jLabel49.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        jLabel49.setText("Thông tin đặt vé");

        jLabel50.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        jLabel50.setText("Thông tin khách hàng");

        jLabel18.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel18.setText("Họ và tên");

        jLabel51.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel51.setText("SĐT");

        jLabel23.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel23.setText("Số CMND ");
        jLabel23.setToolTipText("");

        jLabel52.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel52.setText("Email");

        jLabel16.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel16.setText("VNĐ");

        jLabel17.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel17.setText("ông/bà: ");

        hoten1.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        hoten1.setText("jLabel22");

        jLabel24.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel24.setText("Có mã vé:");

        maveform.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        maveform.setText("jLabel24");

        sdt.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        sdt.setText("jLabel27");

        hoten2.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        hoten2.setText("jLabel27");

        cmnd.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        cmnd.setText("jLabel27");

        email.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        email.setText("jLabel27");

        jLabel53.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel53.setText("Vị trí ghế:");

        vitrighe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        vitrighe.setText("jLabel27");

        jLabel55.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        jLabel55.setText("Thông tin hoàn vé");

        email1.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        email1.setText("jLabel27");

        email2.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        email2.setText("jLabel27");

        email3.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        email3.setText("jLabel27");

        email4.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        email4.setText("Giá vé");

        email5.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        email5.setText("Phí hoàn vé");

        email6.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        email6.setText("Tiền hoàn vé");

        javax.swing.GroupLayout VeLayout = new javax.swing.GroupLayout(Ve);
        Ve.setLayout(VeLayout);
        VeLayout.setHorizontalGroup(
            VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(VeLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VeLayout.createSequentialGroup()
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49)
                            .addComponent(jLabel43)
                            .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel42))
                            .addComponent(jLabel44)
                            .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel46))
                            .addComponent(jLabel53))
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(diemlenxe)
                                .addComponent(tuyenxe)
                                .addComponent(diemxuongxe)
                                .addComponent(biensoxe)
                                .addComponent(thoigiankhoihanh))
                            .addGroup(VeLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vitrighe)
                                    .addComponent(thoigianden)
                                    .addComponent(loaixe)
                                    .addGroup(VeLayout.createSequentialGroup()
                                        .addComponent(giave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)))))
                        .addGap(41, 41, 41)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VeLayout.createSequentialGroup()
                                    .addComponent(jLabel51)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sdt))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VeLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hoten2))
                                .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VeLayout.createSequentialGroup()
                                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel52))
                                .addGap(18, 18, 18)
                                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email)
                                    .addComponent(cmnd)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(VeLayout.createSequentialGroup()
                                    .addComponent(email6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(email3)
                                    .addGap(12, 12, 12))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VeLayout.createSequentialGroup()
                                    .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(email5)
                                        .addComponent(email4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(email1)
                                        .addComponent(email2))))))
                    .addGroup(VeLayout.createSequentialGroup()
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(VeLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VeLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hoten1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24)))
                        .addGap(18, 18, 18)
                        .addComponent(maveform)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        VeLayout.setVerticalGroup(
            VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VeLayout.createSequentialGroup()
                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VeLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(maveform))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel50))
                    .addGroup(VeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(hoten1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel49))
                    .addGroup(VeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(tuyenxe)
                    .addComponent(jLabel18)
                    .addComponent(hoten2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(diemlenxe)
                    .addComponent(jLabel51)
                    .addComponent(sdt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VeLayout.createSequentialGroup()
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(diemxuongxe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biensoxe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(thoigiankhoihanh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(thoigianden, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(vitrighe)))
                    .addGroup(VeLayout.createSequentialGroup()
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(cmnd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(email))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(email1)
                            .addComponent(email4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VeLayout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VeLayout.createSequentialGroup()
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loaixe)
                            .addComponent(email5)
                            .addComponent(email2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(giave)
                            .addComponent(jLabel16)
                            .addComponent(email6)
                            .addComponent(email3))))
                .addGap(71, 71, 71)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(332, Short.MAX_VALUE)
                    .addComponent(Ve, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(59, Short.MAX_VALUE)
                    .addComponent(Ve, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(116, Short.MAX_VALUE)))
        );

        Ve.getAccessibleContext().setAccessibleName("500");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemActionPerformed
        // TODO add your handling code here:
        String maDatVe = null;
        String hoTen = null;
        String tenTuyen = null;
        String diemDau = null;
        String diemCuoi = null;
        String bienSo = null;
        String viTriGhe = null;
        String thoiGianKH = null;
        String thoiGianDen = null;
        String tenLoaiXe = null;
        String tongTien = null;
        String sDT = null;
        String cMND = null;
        String eMail = null;
        String giaVe = null;
        String phihoanve = null;
        String tienhoanve = null;

        try {
            Class.forName("oracle.jdbc.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##TEST3", "Square1");
            Statement st = conn.createStatement();
            String sql = "select max(ID_DATVE) mave \n"
                    + "from DATVE ";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                maDatVe = rs.getString("mave");
            }

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        maveform.setText(maDatVe);

        try {
            Class.forName("oracle.jdbc.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##TEST3", "Square1");

            pst = conn.prepareStatement("SELECT H.TENHK, T.TENTUYEN, T.DIEMDAU, T. DIEMCUOI, X.BIENSO, V.VITRIGHE,\n"
                    + "    C.THOIGIANKH, C.THOIGIANDEN, L.TENLOAIXE, D.TONGTIEN, H.SDT, H.CMND, H.EMAIL\n"
                    + "FROM (((((DATVE D JOIN VE v ON V.ID_VE=D.ID_VE)\n"
                    + "    JOIN HANHKHACH H ON D.ID_HANHKHACH=H.ID_HANHKHACH)\n"
                    + "    JOIN CHUYENXE C ON C.ID_CHUYENXE = V.ID_CHUYENXE)\n"
                    + "    JOIN XE X ON X.ID_XE = C.ID_XE)\n"
                    + "    JOIN LOAIXE L ON L.ID_LOAIXE=X.ID_LOAIXE)\n"
                    + "    JOIN TUYENXE t ON t.ID_TUYENXE=C.ID_tuyenxe\n"
                    + "WHERE D.ID_DATVE=?");

            pst.setString(1, maDatVe);

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                hoTen = rs.getString("TENHK");
                tenTuyen = rs.getString("TENTUYEN");
                diemDau = rs.getString("DIEMDAU");
                diemCuoi = rs.getString("DIEMCUOI");
                bienSo = rs.getString("BIENSO");
                viTriGhe = rs.getString("VITRIGHE");
                thoiGianKH = rs.getString("THOIGIANKH");
                thoiGianDen = rs.getString("THOIGIANDEN");
                tenLoaiXe = rs.getString("TENLOAIXE");
                tongTien = rs.getString("TONGTIEN");
                sDT = rs.getString("SDT");
                cMND = rs.getString("CMND");
                eMail = rs.getString("EMAIL");
                giaVe = rs.getString("GIAVE");
                phihoanve = rs.getString("CMND");
                tienhoanve = rs.getString("EMAIL");
                thoigiankhoihanh.setText(String.valueOf(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(rs.getTimestamp("THOIGIANKH"))));
                thoigianden.setText(String.valueOf(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(rs.getTimestamp("THOIGIANDEN"))));
                Ve.setVisible(false);
                Them.setVisible(false);
            }

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        tuyenxe.setText(tenTuyen);
        diemlenxe.setText(diemDau);
        diemxuongxe.setText(diemCuoi);
        biensoxe.setText(bienSo);
        vitrighe.setText(viTriGhe);

        loaixe.setText(tenLoaiXe);
        giave.setText(tongTien);
        hoten1.setText(hoTen);
        hoten2.setText(hoTen);
        sdt.setText(sDT);
        cmnd.setText(cMND);
        email.setText(eMail);
        Ve.setVisible(true);
        Them.setVisible(true);
        IDDve.setVisible(false);
        IDDatve.setVisible(false);
        IDnv.setVisible(false);
        IDNhanVien.setVisible(false);
        TimKiem.setVisible(false);

    }//GEN-LAST:event_TimKiemActionPerformed

    private void IDnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDnvActionPerformed

    private void trolaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trolaiActionPerformed
        // TODO add your handling code here:
        QuanLyHoanVe quanlyhoanve = new QuanLyHoanVe();
        quanlyhoanve.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_trolaiActionPerformed

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        //        // TODO add your handling code here:
        int count = 1;

        String iddatve = IDDatve.getText();
        String idnhanvien = IDnv.getSelectedItem().toString();
        boolean flag = true;
        if (iddatve.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ID Đặt vé");
            flag = false;
        }
        if (flag == true) {
            String reg = "\\d{5}";
            boolean flag2 = iddatve.matches(reg);
            if (flag2 == false) {
                JOptionPane.showMessageDialog(this, "ID Đặt vé không đúng hoặc không hợp lệ");
                flag = false;
            } else {

            }
        }
        if (flag == true) {
            try {
                Connection conn = CheckOracleConnection.getMyConnection();
                String sql = "SELECT ID_DATVE FROM DATVE WHERE ID_DATVE='" + iddatve + "'";
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy đặt vé");
                    flag = false;
                }
            } catch (ClassNotFoundException | SQLException e) {
                System.out.println(e);

            }
        }
        if (flag == true) {
            try {
                Connection conn = CheckOracleConnection.getMyConnection();
                String sql = "SELECT TINHTRANG FROM DATVE WHERE TINHTRANG = 'Đã hoàn'";
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                } else {
                    JOptionPane.showMessageDialog(this, "Vé đã được hoàn");
                    flag = false;
                }
            } catch (ClassNotFoundException | SQLException e) {
                System.out.println(e);

            }
        }

        if (flag == true) {
            try {
                Ve a = new Ve();
                count = a.ThemHoanVe(iddatve, idnhanvien);
                if (count == 0) {
                    JOptionPane.showMessageDialog(this, "Không thành công  ");

                } else if (count > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }

    }//GEN-LAST:event_ThemActionPerformed

    private void ThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ThemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Them_HoanVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Them_HoanVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Them_HoanVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Them_HoanVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Them_HoanVe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A;
    private javax.swing.JPanel B;
    private javax.swing.JPanel DangXuat;
    private javax.swing.JPanel Home2;
    private javax.swing.JTextField IDDatve;
    private javax.swing.JLabel IDDve;
    private javax.swing.JLabel IDNhanVien;
    private javax.swing.JComboBox<String> IDnv;
    private javax.swing.JLabel Logo2;
    private javax.swing.JPanel QL_GiaVe;
    private javax.swing.JPanel QL_GiaVe2;
    private javax.swing.JPanel QL_GiaVe6;
    private javax.swing.JButton Them;
    private javax.swing.JButton TimKiem;
    private javax.swing.JPanel Ve;
    public javax.swing.JLabel biensoxe;
    public javax.swing.JLabel cmnd;
    public javax.swing.JLabel diemlenxe;
    public javax.swing.JLabel diemxuongxe;
    public javax.swing.JLabel email;
    public javax.swing.JLabel email1;
    public javax.swing.JLabel email2;
    public javax.swing.JLabel email3;
    public javax.swing.JLabel email4;
    public javax.swing.JLabel email5;
    public javax.swing.JLabel email6;
    public javax.swing.JLabel giave;
    public javax.swing.JLabel hoten1;
    public javax.swing.JLabel hoten2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JLabel loaixe;
    public javax.swing.JLabel maveform;
    public javax.swing.JLabel sdt;
    public javax.swing.JLabel thoigianden;
    public javax.swing.JLabel thoigiankhoihanh;
    private javax.swing.JButton trolai;
    public javax.swing.JLabel tuyenxe;
    public javax.swing.JLabel vitrighe;
    // End of variables declaration//GEN-END:variables

}
