/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.NhanVien.HoanVe;

import Process.NhanVien.Ve;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.lang.model.util.Types;
import ConnectDB.CheckOracleConnection;
import View.Home.Login_Form;
import View.NhanVien.DatVe.Homepage_QuanLyDatVe;
import View.NhanVien.HanhKhach.QuanLyHanhKhach;
import View.NhanVien.Homepage_NguoiNhanVien;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.CallableStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

/**
 *
 * @author DUNG
 */
public class ThemHoanVe extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ThemHoanVe() {
        initComponents();
        ComboboxIDnhanvien();
        Ve.setVisible(false);
        Ve.setVisible(false);
        IDNhanVien.setVisible(false);
        IDnv.setVisible(false);
        Them.setVisible(false);
    }
    Connection conn;
    PreparedStatement pst;

    public void CloseFrame() {
        super.dispose();
    }

    public void ComboboxIDnhanvien() {
        try {
            Connection conn = CheckOracleConnection.getMyConnection();
            String sql = "SELECT ID_NHANVIEN FROM NHANVIEN";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                IDnv.addItem(rs.getString("ID_NHANVIEN"));
            }
            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        Them = new javax.swing.JButton();
        trolai = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        IDNhanVien = new javax.swing.JLabel();
        IDDve = new javax.swing.JLabel();
        IDnv = new javax.swing.JComboBox<>();
        TimKiem = new javax.swing.JButton();
        IDDatve = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Ve = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        tuyenxe = new javax.swing.JLabel();
        diemlenxe = new javax.swing.JLabel();
        diemxuongxe = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        biensoxe = new javax.swing.JLabel();
        thoigiankhoihanh = new javax.swing.JLabel();
        thoigianden = new javax.swing.JLabel();
        giave = new javax.swing.JLabel();
        loaixe = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hoten1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        maveform = new javax.swing.JLabel();
        sdt = new javax.swing.JLabel();
        hoten2 = new javax.swing.JLabel();
        cmnd = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        vitrighe = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        GiaVe = new javax.swing.JLabel();
        PhiHV = new javax.swing.JLabel();
        TienHV = new javax.swing.JLabel();
        email4 = new javax.swing.JLabel();
        email5 = new javax.swing.JLabel();
        email6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        A = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        trangChu_homepage = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dangXuat_homepage = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B.setBackground(new java.awt.Color(251, 250, 238));
        B.setPreferredSize(new java.awt.Dimension(680, 500));

        jLabel54.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel54.setText("Mời thêm hoàn vé!");

        jPanel7.setBackground(new java.awt.Color(251, 250, 238));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 151, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(288, 288, 288))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(58, 58, 58))
        );

        Them.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/NhanVien/icons8_transaction_20px.png"))); // NOI18N
        Them.setText("Hoàn vé");
        Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThemMouseClicked(evt);
            }
        });
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        trolai.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        trolai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/QuanLy/Icon/QuanLyTuyenXe/icons8_return_30px.png"))); // NOI18N
        trolai.setText("Trở lại");
        trolai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trolaiActionPerformed(evt);
            }
        });

        jLabel59.setFont(new java.awt.Font("Lora", 2, 14)); // NOI18N
        jLabel59.setText("Sự hài lòng của quý khách");

        jLabel22.setFont(new java.awt.Font("Lora", 2, 14)); // NOI18N
        jLabel22.setText("là minh chứng cho chất lượng dịch vụ của hãng xe Thanh Xuân");

        IDNhanVien.setFont(new java.awt.Font("Lora", 0, 14)); // NOI18N
        IDNhanVien.setText("ID nhân viên ");

        IDDve.setFont(new java.awt.Font("Lora", 0, 14)); // NOI18N
        IDDve.setText("ID đặt vé");

        IDnv.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        IDnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDnvActionPerformed(evt);
            }
        });

        TimKiem.setText("Tìm kiếm");
        TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemActionPerformed(evt);
            }
        });

        IDDatve.setPreferredSize(new java.awt.Dimension(64, 23));
        IDDatve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDDatveActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(205, 247, 247));

        Ve.setBackground(new java.awt.Color(205, 247, 247));
        Ve.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        Ve.setPreferredSize(new java.awt.Dimension(500, 390));

        jLabel35.setFont(new java.awt.Font("Lora Medium", 1, 14)); // NOI18N
        jLabel35.setText("Hãng xe khách Thanh Xuân");

        jLabel41.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel41.setText("Tuyến xe:");

        jLabel42.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel42.setText("Điểm lên xe:");

        jLabel43.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel43.setText("Điểm xuống xe:");

        jLabel44.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel44.setText("Biển số xe:");

        jLabel45.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel45.setText("Thời gian khởi hành:");

        jLabel46.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel46.setText("Thời gian đến:");

        tuyenxe.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        tuyenxe.setText("jLabel27");

        diemlenxe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        diemlenxe.setText("jLabel27");

        diemxuongxe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        diemxuongxe.setText("jLabel27");

        jLabel47.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel47.setText("Giá vé: ");

        jLabel48.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel48.setText("Loại xe:");

        biensoxe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        biensoxe.setText("jLabel27");

        thoigiankhoihanh.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        thoigiankhoihanh.setText("jLabel27");

        thoigianden.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        thoigianden.setText("jLabel27");

        giave.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        giave.setText("jLabel27");

        loaixe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        loaixe.setText("jLabel27");

        jLabel49.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        jLabel49.setText("Thông tin đặt vé");

        jLabel50.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        jLabel50.setText("Thông tin khách hàng");

        jLabel18.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel18.setText("Họ và tên:");

        jLabel51.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel51.setText("SĐT:");

        jLabel23.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel23.setText("Số CMND: ");
        jLabel23.setToolTipText("");

        jLabel52.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel52.setText("Email:");

        jLabel16.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel16.setText("VNĐ");

        jLabel17.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel17.setText("ông/bà: ");

        hoten1.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        hoten1.setText("jLabel22");

        jLabel24.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel24.setText("Có mã vé:");

        maveform.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        maveform.setText("jLabel24");

        sdt.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        sdt.setText("jLabel27");

        hoten2.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        hoten2.setText("jLabel27");

        cmnd.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        cmnd.setText("jLabel27");

        email.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        email.setText("jLabel27");

        jLabel53.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel53.setText("Vị trí ghế:");

        vitrighe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        vitrighe.setText("jLabel27");

        jLabel55.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        jLabel55.setText("Thông tin hoàn vé");

        GiaVe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        GiaVe.setText("jLabel27");

        PhiHV.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        PhiHV.setText("jLabel27");

        TienHV.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        TienHV.setText("jLabel27");

        email4.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        email4.setText("Giá vé:");

        email5.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        email5.setText("Phí hoàn vé:");

        email6.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        email6.setText("Tiền hoàn vé:");

        javax.swing.GroupLayout VeLayout = new javax.swing.GroupLayout(Ve);
        Ve.setLayout(VeLayout);
        VeLayout.setHorizontalGroup(
            VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VeLayout.createSequentialGroup()
                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(VeLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel35))
                    .addGroup(VeLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addGroup(VeLayout.createSequentialGroup()
                                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel43)
                                    .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel42))
                                    .addComponent(jLabel44)
                                    .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel46))
                                    .addComponent(jLabel53))
                                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VeLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(VeLayout.createSequentialGroup()
                                                    .addComponent(giave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel16))
                                                .addComponent(biensoxe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(diemxuongxe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(diemlenxe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tuyenxe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(loaixe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vitrighe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(VeLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(thoigianden, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VeLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thoigiankhoihanh, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(VeLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hoten1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VeLayout.createSequentialGroup()
                                .addComponent(email6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TienHV, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel55)
                            .addComponent(jLabel50)
                            .addGroup(VeLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(maveform, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VeLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(21, 21, 21)
                                .addComponent(hoten2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VeLayout.createSequentialGroup()
                                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel51)
                                    .addComponent(jLabel52))
                                .addGap(18, 18, 18)
                                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(VeLayout.createSequentialGroup()
                                .addComponent(email5)
                                .addGap(18, 18, 18)
                                .addComponent(PhiHV, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VeLayout.createSequentialGroup()
                                .addComponent(email4)
                                .addGap(49, 49, 49)
                                .addComponent(GiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        VeLayout.setVerticalGroup(
            VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addGap(12, 12, 12)
                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(maveform)
                    .addComponent(jLabel17)
                    .addComponent(hoten1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VeLayout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VeLayout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel42)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel53)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel47))
                            .addGroup(VeLayout.createSequentialGroup()
                                .addComponent(tuyenxe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(VeLayout.createSequentialGroup()
                                        .addComponent(diemlenxe)
                                        .addGap(14, 14, 14)
                                        .addComponent(diemxuongxe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(biensoxe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thoigiankhoihanh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thoigianden, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vitrighe)
                                        .addGap(46, 46, 46))
                                    .addGroup(VeLayout.createSequentialGroup()
                                        .addComponent(loaixe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(giave)
                                            .addComponent(jLabel16)))))))
                    .addGroup(VeLayout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(hoten2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51)
                            .addComponent(sdt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(cmnd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(email))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email4)
                            .addComponent(GiaVe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email5)
                            .addComponent(PhiHV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email6)
                            .addComponent(TienHV))
                        .addGap(23, 23, 23)))
                .addGap(28, 28, 28))
        );

        jSeparator5.setForeground(new java.awt.Color(205, 247, 247));

        javax.swing.GroupLayout BLayout = new javax.swing.GroupLayout(B);
        B.setLayout(BLayout);
        BLayout.setHorizontalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BLayout.createSequentialGroup()
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel54))
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BLayout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addGap(120, 120, 120))
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IDDve)
                            .addComponent(Them))
                        .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BLayout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(trolai))
                            .addGroup(BLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDDatve, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(IDNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDnv, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BLayout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(Ve, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1011, Short.MAX_VALUE)))
        );
        BLayout.setVerticalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDDve, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDDatve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(TimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BLayout.createSequentialGroup()
                        .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trolai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(15, 15, 15))
            .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BLayout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(Ve, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(165, Short.MAX_VALUE)))
        );

        A.setBackground(new java.awt.Color(205, 247, 247));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/HÃNG XE KHÁCH (200 × 200 px).png"))); // NOI18N

        trangChu_homepage.setBackground(new java.awt.Color(251, 250, 238));
        trangChu_homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trangChu_homepageMouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_home_page_20px_1.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel14.setText("Trang chủ");

        javax.swing.GroupLayout trangChu_homepageLayout = new javax.swing.GroupLayout(trangChu_homepage);
        trangChu_homepage.setLayout(trangChu_homepageLayout);
        trangChu_homepageLayout.setHorizontalGroup(
            trangChu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChu_homepageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trangChu_homepageLayout.setVerticalGroup(
            trangChu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChu_homepageLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(trangChu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(251, 250, 238));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16QuanLyHanhKhachMouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_management_20px_1.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel21.setText("Quản lý hành khách");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(30, 30, 30)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(251, 250, 238));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17QuanLyDatVeMouseClicked(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/NhanVien/icons8_ticket_confirmed_20px.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel27.setText("Quản lý đặt vé");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(30, 30, 30)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(153, 153, 255));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/NhanVien/icons8_transaction_20px.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel25.setText("Quản lý hoàn vé");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(30, 30, 30)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel25))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dangXuat_homepage.setBackground(new java.awt.Color(251, 250, 238));
        dangXuat_homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangXuat_homepageMouseClicked(evt);
            }
        });

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_Logout_20px_3.png"))); // NOI18N

        jLabel36.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel36.setText("Đăng xuất");

        javax.swing.GroupLayout dangXuat_homepageLayout = new javax.swing.GroupLayout(dangXuat_homepage);
        dangXuat_homepage.setLayout(dangXuat_homepageLayout);
        dangXuat_homepageLayout.setHorizontalGroup(
            dangXuat_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangXuat_homepageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(30, 30, 30)
                .addComponent(jLabel36)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dangXuat_homepageLayout.setVerticalGroup(
            dangXuat_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangXuat_homepageLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(dangXuat_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel36))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ALayout = new javax.swing.GroupLayout(A);
        A.setLayout(ALayout);
        ALayout.setHorizontalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ALayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALayout.createSequentialGroup()
                        .addGroup(ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dangXuat_homepage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trangChu_homepage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11))))
        );
        ALayout.setVerticalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(trangChu_homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dangXuat_homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ThemMouseClicked

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        //        // TODO add your handling code here:
        int A = -1;
        int B = -1;
        String iddatve = IDDatve.getText();
        String idnhanvien = IDnv.getSelectedItem().toString();
        try {
            Ve a = new Ve();
            A = a.DieuKienHoanVe(iddatve);
            if (A == 0) {
                JOptionPane.showMessageDialog(this, "Vé không thỏa điều kiện để hoàn");

            } 
            else if (A > 0) {
                try {
                    B = a.ThemHoanVe(iddatve, idnhanvien);
                    if (B == 0) {
                        JOptionPane.showMessageDialog(this, "Hoàn vé không thành công  ");
                    } else if (B > 0) {
                        JOptionPane.showMessageDialog(this, "Hoàn vé thành công");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Kiểm tra không thành công  ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }


    }//GEN-LAST:event_ThemActionPerformed

    private void trolaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trolaiActionPerformed
        // TODO add your handling code here:
        Homepage_QuanLyHoanVe quanlyhoanve = new Homepage_QuanLyHoanVe();
        quanlyhoanve.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_trolaiActionPerformed

    private void IDnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDnvActionPerformed

    private void TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemActionPerformed
        // TODO add your handling code here:
        String maDatVe = null;
        String hoTen = null;
        String tenTuyen = null;
        String diemDau = null;
        String diemCuoi = null;
        String bienSo = null;
        String viTriGhe = null;
        String thoiGianKH = null;
        String thoiGianDen = null;
        String tenLoaiXe = null;
        String tongTien = null;
        String maVe = null;
        String sDT = null;
        String cMND = null;
        String eMail = null;
        Double giaVe = null;
        Double phihoanve = null;
        Double tienhoanve = null;
        String iddatve = IDDatve.getText();
        boolean flag = true;
        if (iddatve.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ID Đặt vé");
            flag = false;
        }
        if (flag == true) {
            String reg = "\\d{5}";
            boolean flag2 = iddatve.matches(reg);
            if (flag2 == false) {
                JOptionPane.showMessageDialog(this, "ID Đặt vé không đúng hoặc không hợp lệ");
                flag = false;
            }
        }
        if (flag == true) {
            try {
                Connection conn = CheckOracleConnection.getMyConnection();
                String sql = "SELECT ID_DATVE FROM DATVE WHERE ID_DATVE='" + iddatve + "'";
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {

                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy đặt vé");
                    flag = false;
                }
            } catch (SQLException ex) {
            } catch (ClassNotFoundException ex) {
            }

        }
        if (flag == true) {
            try {
                Connection conn = CheckOracleConnection.getMyConnection();
                String sql = "SELECT TINHTRANG FROM DATVE WHERE TINHTRANG = 'Đã hoàn'";
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                } else {
                    JOptionPane.showMessageDialog(this, "Vé đã được hoàn");
                    flag = false;
                }
            } catch (ClassNotFoundException | SQLException e) {
                System.out.println(e);

            }
        }
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##TEST3", "Square1");
            Statement st = conn.createStatement();
            String sql = "select max(ID_DATVE) mave \n"
                    + "from DATVE ";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                maDatVe = rs.getString("mave");
            }

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            Class.forName("oracle.jdbc.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##TEST3", "Square1");

            pst = conn.prepareStatement("SELECT H.TENHK, V.ID_VE, T.TENTUYEN, T.DIEMDAU, T. DIEMCUOI, X.BIENSO, V.VITRIGHE,\n"
                    + "    C.THOIGIANKH, C.THOIGIANDEN, L.TENLOAIXE, D.TONGTIEN, H.SDT, H.CMND, H.EMAIL, E.GIAVE\n"
                    + "FROM ((((((DATVE D JOIN VE v ON V.ID_VE=D.ID_VE)\n"
                    + "    JOIN HANHKHACH H ON D.ID_HANHKHACH=H.ID_HANHKHACH)\n"
                    + "    JOIN CHUYENXE C ON C.ID_CHUYENXE = V.ID_CHUYENXE)\n"
                    + "    JOIN XE X ON X.ID_XE = C.ID_XE)\n"
                    + "    JOIN LOAIXE L ON L.ID_LOAIXE=X.ID_LOAIXE)\n"
                    + "    JOIN TUYENXE t ON t.ID_TUYENXE=C.ID_tuyenxe)\n"
                    + "    JOIN GIAVE E ON E.ID_TUYENXE=C.ID_tuyenxe\n"
                    + "WHERE D.ID_DATVE=?");
            pst.setString(1, iddatve);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                maVe = rs.getString("ID_VE");
                hoTen = rs.getString("TENHK");
                tenTuyen = rs.getString("TENTUYEN");
                diemDau = rs.getString("DIEMDAU");
                diemCuoi = rs.getString("DIEMCUOI");
                bienSo = rs.getString("BIENSO");
                viTriGhe = rs.getString("VITRIGHE");
                thoiGianKH = rs.getString("THOIGIANKH");
                thoiGianDen = rs.getString("THOIGIANDEN");
                tenLoaiXe = rs.getString("TENLOAIXE");
                tongTien = rs.getString("TONGTIEN");
                sDT = rs.getString("SDT");
                cMND = rs.getString("CMND");
                eMail = rs.getString("EMAIL");
                giaVe = rs.getDouble("GIAVE");
                phihoanve = 0.2 * rs.getDouble("GIAVE");
                tienhoanve = 0.8 * rs.getDouble("GIAVE");
                thoigiankhoihanh.setText(String.valueOf(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(rs.getTimestamp("THOIGIANKH"))));
                thoigianden.setText(String.valueOf(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(rs.getTimestamp("THOIGIANDEN"))));
            }

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        tuyenxe.setText(tenTuyen);
        diemlenxe.setText(diemDau);
        diemxuongxe.setText(diemCuoi);
        biensoxe.setText(bienSo);
        vitrighe.setText(viTriGhe);
        maveform.setText(maVe);
        loaixe.setText(tenLoaiXe);
        giave.setText(tongTien);
        hoten1.setText(hoTen);
        hoten2.setText(hoTen);
        sdt.setText(sDT);
        cmnd.setText(cMND);
        email.setText(eMail);
        GiaVe.setText(String.valueOf(giaVe));
        PhiHV.setText(String.valueOf(phihoanve));
        TienHV.setText(String.valueOf(tienhoanve));
        Ve.setVisible(true);
        Ve.setVisible(true);
        Them.setVisible(true);
        IDDve.setVisible(false);
        IDDatve.setVisible(false);
        IDnv.setVisible(true);
        IDNhanVien.setVisible(true);
        TimKiem.setVisible(false);
    }//GEN-LAST:event_TimKiemActionPerformed

    private void IDDatveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDDatveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDDatveActionPerformed

    private void trangChu_homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trangChu_homepageMouseClicked
        // TODO add your handling code here:
        Homepage_NguoiNhanVien nhanvien = new Homepage_NguoiNhanVien();
        nhanvien.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_trangChu_homepageMouseClicked

    private void jPanel16QuanLyHanhKhachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16QuanLyHanhKhachMouseClicked
        // TODO add your handling code here:
        QuanLyHanhKhach quanlyhanhkhach = new QuanLyHanhKhach();
        quanlyhanhkhach.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jPanel16QuanLyHanhKhachMouseClicked

    private void jPanel17QuanLyDatVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17QuanLyDatVeMouseClicked
        // TODO add your handling code here:
        Homepage_QuanLyDatVe quanlydatve = new Homepage_QuanLyDatVe();
        quanlydatve.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jPanel17QuanLyDatVeMouseClicked

    private void dangXuat_homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangXuat_homepageMouseClicked
        // TODO add your handling code here:
        Login_Form login = new Login_Form();
        login.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_dangXuat_homepageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemHoanVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemHoanVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemHoanVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemHoanVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemHoanVe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A;
    private javax.swing.JPanel B;
    public javax.swing.JLabel GiaVe;
    private javax.swing.JTextField IDDatve;
    private javax.swing.JLabel IDDve;
    private javax.swing.JLabel IDNhanVien;
    private javax.swing.JComboBox<String> IDnv;
    public javax.swing.JLabel PhiHV;
    private javax.swing.JButton Them;
    public javax.swing.JLabel TienHV;
    private javax.swing.JButton TimKiem;
    private javax.swing.JPanel Ve;
    public javax.swing.JLabel biensoxe;
    public javax.swing.JLabel cmnd;
    private javax.swing.JPanel dangXuat_homepage;
    public javax.swing.JLabel diemlenxe;
    public javax.swing.JLabel diemxuongxe;
    public javax.swing.JLabel email;
    public javax.swing.JLabel email4;
    public javax.swing.JLabel email5;
    public javax.swing.JLabel email6;
    public javax.swing.JLabel giave;
    public javax.swing.JLabel hoten1;
    public javax.swing.JLabel hoten2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel loaixe;
    public javax.swing.JLabel maveform;
    public javax.swing.JLabel sdt;
    public javax.swing.JLabel thoigianden;
    public javax.swing.JLabel thoigiankhoihanh;
    private javax.swing.JPanel trangChu_homepage;
    private javax.swing.JButton trolai;
    public javax.swing.JLabel tuyenxe;
    public javax.swing.JLabel vitrighe;
    // End of variables declaration//GEN-END:variables
}
