/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.NhanVien.DatVe;

import View.KhachHang.*;
import Process.KhachHang.DatVe.DatVe;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author duyta
 */
public class ThemXuatVe extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public ThemXuatVe() {
        initComponents();
        this.setResizable(false);
        fillForm();

    }
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        trangChu_homepage = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        datVe_Homepage = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        gioiThieu_homepage = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        tuyenxe = new javax.swing.JLabel();
        diemlenxe = new javax.swing.JLabel();
        diemxuongxe = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        biensoxe = new javax.swing.JLabel();
        thoigiankhoihanh = new javax.swing.JLabel();
        thoigianden = new javax.swing.JLabel();
        giave = new javax.swing.JLabel();
        loaixe = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hoten1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        maveform = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        sdt = new javax.swing.JLabel();
        hoten2 = new javax.swing.JLabel();
        cmnd = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        vitrighe = new javax.swing.JLabel();
        nuttrangchu_datve = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(205, 247, 247));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/HÃNG XE KHÁCH (200 × 200 px).png"))); // NOI18N

        trangChu_homepage.setBackground(new java.awt.Color(251, 250, 238));
        trangChu_homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trangChu_homepageMouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_home_page_20px_1.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel14.setText("Trang chủ");

        javax.swing.GroupLayout trangChu_homepageLayout = new javax.swing.GroupLayout(trangChu_homepage);
        trangChu_homepage.setLayout(trangChu_homepageLayout);
        trangChu_homepageLayout.setHorizontalGroup(
            trangChu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChu_homepageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trangChu_homepageLayout.setVerticalGroup(
            trangChu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChu_homepageLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(trangChu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        datVe_Homepage.setBackground(new java.awt.Color(153, 153, 255));
        datVe_Homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datVe_HomepageMouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_ticket_20px_1.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel21.setText("Đặt vé");

        javax.swing.GroupLayout datVe_HomepageLayout = new javax.swing.GroupLayout(datVe_Homepage);
        datVe_Homepage.setLayout(datVe_HomepageLayout);
        datVe_HomepageLayout.setHorizontalGroup(
            datVe_HomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datVe_HomepageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(30, 30, 30)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        datVe_HomepageLayout.setVerticalGroup(
            datVe_HomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datVe_HomepageLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(datVe_HomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datVe_Homepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(trangChu_homepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trangChu_homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datVe_Homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        gioiThieu_homepage.setBackground(new java.awt.Color(251, 250, 238));

        jSeparator1.setForeground(new java.awt.Color(205, 247, 247));

        jLabel5.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel5.setText("Địa chỉ: 9-9A Tình Duyên, phường Thanh Xuân, TP Hồ Chí Minh");

        jLabel4.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel4.setText("CÔNG TY CỔ PHẦN XE KHÁCH THANH XUÂN");

        jLabel3.setFont(new java.awt.Font("Comfortaa Medium", 1, 18)); // NOI18N
        jLabel3.setText("1900 7979");
        jLabel3.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel2.setText("TỔNG ĐÀI CHĂM SÓC KHÁCH HÀNG");

        jLabel6.setFont(new java.awt.Font("Lora", 0, 10)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_fax_20px_6.png"))); // NOI18N
        jLabel6.setText("Fax: 028 7979 6853");

        jLabel7.setFont(new java.awt.Font("Lora", 0, 10)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_mail_20px_3.png"))); // NOI18N
        jLabel7.setText("Email: hotro@thanhxuan.vn");

        jLabel8.setFont(new java.awt.Font("Lora", 0, 10)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_Facebook_20px_4.png"))); // NOI18N
        jLabel8.setText("Facebook: www.facebook.com/xekhachthanhxuan");

        jLabel12.setFont(new java.awt.Font("Lora", 0, 10)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_YouTube_20px_2.png"))); // NOI18N
        jLabel12.setText("Youtube: youtube.com/channel/xekhachthanhxuan");

        jLabel54.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_heart_20px.png"))); // NOI18N
        jLabel54.setText("Xin mời  nhập thông tin đặt vé!!");

        jSeparator3.setForeground(new java.awt.Color(205, 247, 247));

        jPanel4.setBackground(new java.awt.Color(205, 247, 247));

        jLabel35.setFont(new java.awt.Font("Lora Medium", 1, 14)); // NOI18N
        jLabel35.setText("Hãng xe khách Thanh Xuân");

        jLabel41.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel41.setText("Tuyến xe:");

        jLabel42.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel42.setText("Điểm lên xe:");

        jLabel43.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel43.setText("Điểm xuống xe:");

        jLabel44.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel44.setText("Biển số xe:");

        jLabel45.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel45.setText("Thời gian khởi hành:");

        jLabel46.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel46.setText("Thời gian đến:");

        tuyenxe.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        tuyenxe.setText("jLabel27");

        diemlenxe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        diemlenxe.setText("jLabel27");

        diemxuongxe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        diemxuongxe.setText("jLabel27");

        jLabel47.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel47.setText("Giá vé: ");

        jLabel48.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel48.setText("Loại xe:");

        biensoxe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        biensoxe.setText("jLabel27");

        thoigiankhoihanh.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        thoigiankhoihanh.setText("jLabel27");

        thoigianden.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        thoigianden.setText("jLabel27");

        giave.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        giave.setText("jLabel27");

        loaixe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        loaixe.setText("jLabel27");

        jLabel49.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        jLabel49.setText("Thông tin đặt vé");

        jLabel50.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        jLabel50.setText("Thông tin khách hàng");

        jLabel18.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel18.setText("Họ và tên");

        jLabel51.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel51.setText("SĐT");

        jLabel19.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel19.setText("Số CMND ");
        jLabel19.setToolTipText("");

        jLabel52.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel52.setText("Email");

        jLabel16.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel16.setText("VNĐ");

        jLabel9.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel9.setText("xin thông báo");

        jLabel17.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel17.setText("Chúc mừng ông/bà: ");

        hoten1.setFont(new java.awt.Font("Lora Medium", 1, 12)); // NOI18N
        hoten1.setText("jLabel22");

        jLabel23.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel23.setText("Đặt vé thành công với mã vé:");

        maveform.setFont(new java.awt.Font("Lora Medium", 1, 18)); // NOI18N
        maveform.setText("jLabel24");

        jLabel25.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel25.setText(", chi tiết như sau:");

        jLabel26.setFont(new java.awt.Font("Lora Medium", 0, 12)); // NOI18N
        jLabel26.setText("Xin mời ông/ bà tới quầy vé gần nhất của để thực hiện thanh toán.");

        jLabel27.setFont(new java.awt.Font("Lora Medium", 0, 12)); // NOI18N
        jLabel27.setText("Hãng xe khách Thanh Xuân rất vui khi được phục vụ quý khách! ");

        sdt.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        sdt.setText("jLabel27");

        hoten2.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        hoten2.setText("jLabel27");

        cmnd.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        cmnd.setText("jLabel27");

        email.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        email.setText("jLabel27");

        jLabel53.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        jLabel53.setText("Vị trí ghế:");

        vitrighe.setFont(new java.awt.Font("Lora SemiBold", 0, 12)); // NOI18N
        vitrighe.setText("jLabel27");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53)
                            .addComponent(jLabel48)
                            .addComponent(jLabel47)
                            .addComponent(jLabel46)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(thoigianden)
                                    .addComponent(thoigiankhoihanh)
                                    .addComponent(vitrighe)
                                    .addComponent(loaixe)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(giave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel43)
                                            .addComponent(jLabel42)
                                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(diemlenxe)
                                            .addComponent(diemxuongxe)
                                            .addComponent(tuyenxe)
                                            .addComponent(biensoxe)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel49))
                                    .addComponent(jLabel44))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(hoten2))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel52)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel51))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(email)
                                                    .addComponent(sdt)
                                                    .addComponent(cmnd)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel50))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(maveform)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel25))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hoten1)))))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27))
                    .addComponent(jLabel35)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(hoten1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(maveform)
                    .addComponent(jLabel25))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(jLabel50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(tuyenxe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(diemlenxe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(diemxuongxe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(biensoxe)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(hoten2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51)
                            .addComponent(sdt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(cmnd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(email))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(thoigiankhoihanh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(thoigianden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53)
                    .addComponent(vitrighe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(giave)
                                .addComponent(jLabel16))
                            .addComponent(jLabel47)))
                    .addComponent(loaixe))
                .addGap(19, 19, 19)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nuttrangchu_datve.setFont(new java.awt.Font("Lora SemiBold", 1, 14)); // NOI18N
        nuttrangchu_datve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/HanhKhach/Icon/DatGhe/icons8_home_page_30px.png"))); // NOI18N
        nuttrangchu_datve.setText("Trang chủ");
        nuttrangchu_datve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuttrangchu_datveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gioiThieu_homepageLayout = new javax.swing.GroupLayout(gioiThieu_homepage);
        gioiThieu_homepage.setLayout(gioiThieu_homepageLayout);
        gioiThieu_homepageLayout.setHorizontalGroup(
            gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gioiThieu_homepageLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel57))
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(243, 243, 243)
                        .addComponent(jLabel56)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel55))
                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addComponent(jLabel54)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3)
                                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel4))
                                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                                .addGap(131, 131, 131)
                                                .addComponent(jLabel3))
                                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addComponent(jLabel2)))
                                        .addGap(49, 49, 49)
                                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(0, 0, 0)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel11)
                                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addGap(233, 233, 233)
                                        .addComponent(jLabel38)
                                        .addGap(206, 206, 206)
                                        .addComponent(jLabel36))))))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(nuttrangchu_datve)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gioiThieu_homepageLayout.setVerticalGroup(
            gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nuttrangchu_datve))
                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel55))
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel36))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel56)
                                    .addComponent(jLabel57))))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel10)))
                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(gioiThieu_homepage, javax.swing.GroupLayout.PREFERRED_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gioiThieu_homepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trangChu_homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trangChu_homepageMouseClicked
        // TODO add your handling code here:
        Homepage_KhachHang khach = new Homepage_KhachHang();
        khach.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_trangChu_homepageMouseClicked

    private void datVe_HomepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datVe_HomepageMouseClicked
        // TODO add your handling code here:
        ThemXuatVe datve = new ThemXuatVe();
        datve.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_datVe_HomepageMouseClicked

    private void nuttrangchu_datveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuttrangchu_datveActionPerformed
        // TODO add your handling code here:
        Homepage_KhachHang khach = new Homepage_KhachHang();
        khach.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nuttrangchu_datveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemXuatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemXuatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemXuatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemXuatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemXuatVe().setVisible(true);
            }
        });
    }

    public void fillForm() {
        String maDatVe = null;
        String hoTen = null;
        String tenTuyen = null;
        String diemDau = null;
        String diemCuoi = null;
        String bienSo = null;
        String viTriGhe = null;
        String thoiGianKH = null;
        String thoiGianDen = null;
        String tenLoaiXe = null;
        String tongTien = null;
        String sDT = null;
        String cMND = null;
        String eMail = null;

        try {
            Class.forName("oracle.jdbc.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##TEST3", "Square1");
            Statement st = con.createStatement();
            String sql = "select max(ID_DATVE) mave \n"
                    + "from DATVE ";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                maDatVe = rs.getString("mave");
            }

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        maveform.setText(maDatVe);

        try {
            Class.forName("oracle.jdbc.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##TEST3", "Square1");

            pst = con.prepareStatement("SELECT H.TENHK, T.TENTUYEN, T.DIEMDAU, T. DIEMCUOI, X.BIENSO, V.VITRIGHE,\n"
                    + "    C.THOIGIANKH, C.THOIGIANDEN, L.TENLOAIXE, D.TONGTIEN, H.SDT, H.CMND, H.EMAIL\n"
                    + "FROM (((((DATVE D JOIN VE v ON V.ID_VE=D.ID_VE)\n"
                    + "    JOIN HANHKHACH H ON D.ID_HANHKHACH=H.ID_HANHKHACH)\n"
                    + "    JOIN CHUYENXE C ON C.ID_CHUYENXE = V.ID_CHUYENXE)\n"
                    + "    JOIN XE X ON X.ID_XE = C.ID_XE)\n"
                    + "    JOIN LOAIXE L ON L.ID_LOAIXE=X.ID_LOAIXE)\n"
                    + "    JOIN TUYENXE t ON t.ID_TUYENXE=C.ID_tuyenxe\n"
                    + "WHERE D.ID_DATVE=?");

            pst.setString(1, maDatVe);

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                hoTen = rs.getString("TENHK");
                tenTuyen = rs.getString("TENTUYEN");
                diemDau = rs.getString("DIEMDAU");
                diemCuoi = rs.getString("DIEMCUOI");
                bienSo = rs.getString("BIENSO");
                viTriGhe = rs.getString("VITRIGHE");
                thoiGianKH = rs.getString("THOIGIANKH");
                thoiGianDen = rs.getString("THOIGIANDEN");
                tenLoaiXe = rs.getString("TENLOAIXE");
                tongTien = rs.getString("TONGTIEN");
                sDT = rs.getString("SDT");
                cMND = rs.getString("CMND");
                eMail = rs.getString("EMAIL");
                thoigiankhoihanh.setText(String.valueOf(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(rs.getTimestamp("THOIGIANKH"))));
                thoigianden.setText(String.valueOf(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(rs.getTimestamp("THOIGIANDEN"))));
            }

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        tuyenxe.setText(tenTuyen);
        diemlenxe.setText(diemDau);
        diemxuongxe.setText(diemCuoi);
        biensoxe.setText(bienSo);
        vitrighe.setText(viTriGhe);
        
   
        loaixe.setText(tenLoaiXe);
        giave.setText(tongTien);
        hoten1.setText(hoTen);
        hoten2.setText(hoTen);
        sdt.setText(sDT);
        cmnd.setText(cMND);
        email.setText(eMail);  
        
     
        
   }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel biensoxe;
    public javax.swing.JLabel cmnd;
    private javax.swing.JPanel datVe_Homepage;
    public javax.swing.JLabel diemlenxe;
    public javax.swing.JLabel diemxuongxe;
    public javax.swing.JLabel email;
    public javax.swing.JLabel giave;
    private javax.swing.JPanel gioiThieu_homepage;
    public javax.swing.JLabel hoten1;
    public javax.swing.JLabel hoten2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel loaixe;
    public javax.swing.JLabel maveform;
    private javax.swing.JButton nuttrangchu_datve;
    public javax.swing.JLabel sdt;
    public javax.swing.JLabel thoigianden;
    public javax.swing.JLabel thoigiankhoihanh;
    private javax.swing.JPanel trangChu_homepage;
    public javax.swing.JLabel tuyenxe;
    public javax.swing.JLabel vitrighe;
    // End of variables declaration//GEN-END:variables
}
