/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.QuanLy.ChuyenXe;

import Process.QuanLy.TuyenXe.ChuyenXe;
import View.Home.Login_Form;
import View.QuanLy.GiaVe.Homepage_QuanLyGiaVe;
import View.QuanLy.Homepage_NguoiQuanLy;
import View.QuanLy.LoaiXe.Homepage_QuanLyLoaiXe;
import View.QuanLy.NhanVien.Homepage_QuanLyNhanVien;
import View.QuanLy.TuyenXe.Homepage_QuanLyTuyenXe;
import View.QuanLy.TuyenXe.SuaTuyen;
import View.QuanLy.Xe.Homepage_QuanLyXe;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.ResultSetMetaData;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.lang.String;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author duyta
 */
public class SuaChuyen extends javax.swing.JFrame {

    /**
     * Creates new form Homepage_NguoiQuanLy
     */
    public SuaChuyen() {
        this.setResizable(false);
        initComponents();
        fillTable();
        loadcbbdiemdi();
        loadcbbdiemden();
    }

    public void CloseFrame() {
        super.dispose();
    }
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinnerDateEditor2 = new com.toedter.calendar.JSpinnerDateEditor();
        gioiThieu_homepage = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel51 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        nutsua_chuyenxe = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        thoigiankhoihanh = new com.toedter.calendar.JSpinnerDateEditor();
        thoigianden = new com.toedter.calendar.JSpinnerDateEditor();
        taixe = new javax.swing.JTextField();
        phuxe = new javax.swing.JTextField();
        noilenxe = new javax.swing.JTextField();
        noixuongxe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbbdiemdi_chuyenxe = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbbdiemden_chuyenxe = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ngay_chuyenxe = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        nuttim_chuyenxe = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        dschuyenxe_chuyenxe = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        machuyenxe_chuyenxe = new javax.swing.JLabel();
        manql_chuyenxe = new javax.swing.JLabel();
        matuyenxe_chuyenxe = new javax.swing.JLabel();
        maxe_chuyenxe = new javax.swing.JLabel();
        slve_chuyenxe = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        trangChu_homepage8 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        dangXuat_homepage = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gioiThieu_homepage.setBackground(new java.awt.Color(251, 250, 238));
        gioiThieu_homepage.setPreferredSize(new java.awt.Dimension(680, 500));

        jSeparator1.setForeground(new java.awt.Color(205, 247, 247));

        jLabel51.setFont(new java.awt.Font("Lora Medium", 2, 14)); // NOI18N
        jLabel51.setText("Sự hài lòng của quý khách");

        jLabel18.setFont(new java.awt.Font("Lora Medium", 2, 14)); // NOI18N
        jLabel18.setText("là minh chứng cho chất lượng dịch vụ của hãng xe Thanh Xuân");

        jLabel54.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_heart_20px_3.png"))); // NOI18N
        jLabel54.setText("Mời sửa chuyến xe!");

        jSeparator3.setForeground(new java.awt.Color(205, 247, 247));

        jPanel7.setBackground(new java.awt.Color(251, 250, 238));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/QuanLy/Icon/QuanLyTuyenXe/icons8_edit_30px_3.png"))); // NOI18N

        nutsua_chuyenxe.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        nutsua_chuyenxe.setText("Sửa");
        nutsua_chuyenxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutsua_chuyenxeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nutsua_chuyenxe)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nutsua_chuyenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(27, 27, 27))
        );

        jPanel9.setBackground(new java.awt.Color(251, 250, 238));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/QuanLy/Icon/QuanLyTuyenXe/icons8_return_30px.png"))); // NOI18N

        jButton8.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        jButton8.setText("Quay lại");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        jLabel4.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel4.setText("Nhập tên tài xế");

        jLabel10.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel13.setText("Nhập nơi xuống xe");

        jLabel14.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel14.setText("Chọn thời gian khởi hành");

        jLabel15.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel15.setText("Nhập nơi lên xe");

        jLabel17.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel17.setText("Chọn thời gian đến");

        jLabel19.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel19.setText("Nhập tên phụ xe");

        thoigiankhoihanh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));

        thoigianden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));

        taixe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        taixe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));
        taixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taixeActionPerformed(evt);
            }
        });

        phuxe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        phuxe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));
        phuxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phuxeActionPerformed(evt);
            }
        });

        noilenxe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        noilenxe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));

        noixuongxe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        noixuongxe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/QuanLy/Icon/QuanLyTuyenXe/icons8_search_30px_3.png"))); // NOI18N

        cbbdiemdi_chuyenxe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        cbbdiemdi_chuyenxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbdiemdi_chuyenxeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel3.setText("Chọn diểm đi");

        cbbdiemden_chuyenxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbdiemden_chuyenxeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel5.setText("Chọn diểm đến");

        ngay_chuyenxe.setDateFormatString("dd, MM, yyyy ");
        ngay_chuyenxe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel6.setText("Chọn ngày khởi hành");

        nuttim_chuyenxe.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        nuttim_chuyenxe.setText("Tìm kiếm");
        nuttim_chuyenxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuttim_chuyenxeActionPerformed(evt);
            }
        });

        dschuyenxe_chuyenxe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));
        dschuyenxe_chuyenxe.setFont(new java.awt.Font("Lora", 0, 8)); // NOI18N
        dschuyenxe_chuyenxe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chuyến xe", "Mã tuyến xe", "Mã xe", "Mã người quản lý", "Điểm lên xe", "Điểm xuống xe", "Thời gian khởi hành", "Thời gian đến ", "Tài xế", "Phụ xe", "SL vé còn lại "
            }
        ));
        dschuyenxe_chuyenxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dschuyenxe_chuyenxeMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(dschuyenxe_chuyenxe);

        jLabel16.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel16.setText("Mã chuyến xe");

        jLabel28.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel28.setText("Mã tuyến xe");

        jLabel29.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel29.setText("Mã xe");

        jLabel36.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel36.setText("Mã người quản lý");

        jLabel38.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel38.setText("SL vé còn lại");

        machuyenxe_chuyenxe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        machuyenxe_chuyenxe.setText("Mã chuyến xe");

        manql_chuyenxe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        manql_chuyenxe.setText("Mã người quản lý");

        matuyenxe_chuyenxe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        matuyenxe_chuyenxe.setText("Mã tuyến xe");

        maxe_chuyenxe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        maxe_chuyenxe.setText("Mã xe");

        slve_chuyenxe.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        slve_chuyenxe.setText("SL vé còn lại");

        javax.swing.GroupLayout gioiThieu_homepageLayout = new javax.swing.GroupLayout(gioiThieu_homepage);
        gioiThieu_homepage.setLayout(gioiThieu_homepageLayout);
        gioiThieu_homepageLayout.setHorizontalGroup(
            gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(94, 94, 94)
                                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel36)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel28)
                                                    .addComponent(jLabel29)
                                                    .addComponent(jLabel38))
                                                .addGap(18, 18, 18)
                                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(slve_chuyenxe)
                                                    .addComponent(maxe_chuyenxe)
                                                    .addComponent(machuyenxe_chuyenxe)
                                                    .addComponent(manql_chuyenxe)
                                                    .addComponent(matuyenxe_chuyenxe))
                                                .addGap(30, 30, 30)
                                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel15)
                                                    .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel17)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(taixe)
                                                    .addComponent(noixuongxe)
                                                    .addComponent(noilenxe)
                                                    .addComponent(phuxe)
                                                    .addComponent(thoigianden, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                                    .addComponent(thoigiankhoihanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel54))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(14, 14, 14)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                        .addComponent(cbbdiemdi_chuyenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbbdiemden_chuyenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addGap(54, 54, 54)))
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(171, 171, 171))
                                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                        .addComponent(ngay_chuyenxe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nuttim_chuyenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane5)))
                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel51)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gioiThieu_homepageLayout.setVerticalGroup(
            gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gioiThieu_homepageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbbdiemdi_chuyenxe)
                                        .addComponent(cbbdiemden_chuyenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)))
                            .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nuttim_chuyenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ngay_chuyenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(machuyenxe_chuyenxe))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(matuyenxe_chuyenxe))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29)
                                    .addComponent(maxe_chuyenxe))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(manql_chuyenxe))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel38)
                                    .addComponent(slve_chuyenxe)))
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(noilenxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(noixuongxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(thoigiankhoihanh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(thoigianden, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(10, 10, 10)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(taixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phuxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(205, 247, 247));
        jPanel13.setPreferredSize(new java.awt.Dimension(220, 500));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/HÃNG XE KHÁCH (200 × 200 px).png"))); // NOI18N

        trangChu_homepage8.setBackground(new java.awt.Color(251, 250, 238));
        trangChu_homepage8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trangChu_homepageMouseClicked(evt);
            }
        });

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_home_page_20px_1.png"))); // NOI18N

        jLabel53.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel53.setText("Trang chủ");

        javax.swing.GroupLayout trangChu_homepage8Layout = new javax.swing.GroupLayout(trangChu_homepage8);
        trangChu_homepage8.setLayout(trangChu_homepage8Layout);
        trangChu_homepage8Layout.setHorizontalGroup(
            trangChu_homepage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChu_homepage8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52)
                .addGap(30, 30, 30)
                .addComponent(jLabel53)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trangChu_homepage8Layout.setVerticalGroup(
            trangChu_homepage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChu_homepage8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(trangChu_homepage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(251, 250, 238));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLyTuyenXeMouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_map_pinpoint_20px_1.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel21.setText("Quản lý tuyến xe");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(30, 30, 30)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(153, 153, 255));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLyChuyenXeMouseClicked(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_windows_calendar_20px.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel23.setText("Quản lý chuyến xe");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(30, 30, 30)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(251, 250, 238));
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLyXeMouseClicked(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_Shuttle_bus_20px.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel25.setText("Quản lý xe");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(30, 30, 30)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(251, 250, 238));
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLyLoaiXeMouseClicked(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_public_transportation_20px_1.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel27.setText("Quản lý loại xe");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(30, 30, 30)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel21.setBackground(new java.awt.Color(251, 250, 238));
        jPanel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLyNhanVienMouseClicked(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_management_20px_1.png"))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel31.setText("Quản lý nhân viên");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(30, 30, 30)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel22.setBackground(new java.awt.Color(251, 250, 238));
        jPanel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLyGiaVeMouseClicked(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_ticket_20px_1.png"))); // NOI18N

        jLabel33.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel33.setText("Quản lý giá vé");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(30, 30, 30)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dangXuat_homepage.setBackground(new java.awt.Color(251, 250, 238));
        dangXuat_homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangXuat_homepageMouseClicked(evt);
            }
        });

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_Logout_20px_3.png"))); // NOI18N

        jLabel35.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel35.setText("Đăng xuất");

        javax.swing.GroupLayout dangXuat_homepageLayout = new javax.swing.GroupLayout(dangXuat_homepage);
        dangXuat_homepage.setLayout(dangXuat_homepageLayout);
        dangXuat_homepageLayout.setHorizontalGroup(
            dangXuat_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangXuat_homepageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(30, 30, 30)
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dangXuat_homepageLayout.setVerticalGroup(
            dangXuat_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangXuat_homepageLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(dangXuat_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dangXuat_homepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trangChu_homepage8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(trangChu_homepage8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dangXuat_homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gioiThieu_homepage, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gioiThieu_homepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nutsua_chuyenxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutsua_chuyenxeActionPerformed
        // TODO add your handling code here:
        if (thoigiankhoihanh.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn thời gian khởi hành!",
                    "Lỗi thao tác", JOptionPane.WARNING_MESSAGE, null);
        } else if (thoigianden.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn thời gian đên!",
                    "Lỗi thao tác", JOptionPane.WARNING_MESSAGE, null);
        } else {
        DefaultTableModel suachuyenxe = (DefaultTableModel) dschuyenxe_chuyenxe.getModel();
        int i = dschuyenxe_chuyenxe.getSelectedRow();

        if (dschuyenxe_chuyenxe.getSelectedRowCount() == 1) {
            String maChuyenXe = machuyenxe_chuyenxe.getText();
            String maTuyenXe = matuyenxe_chuyenxe.getText();
            String maXe = maxe_chuyenxe.getText();
            String maNQL = manql_chuyenxe.getText();

            String noiLenXe = noilenxe.getText();
            String noiXuongXe = noixuongxe.getText();

            String thoiGianDen = new SimpleDateFormat("dd-MMM-yyyy HH:mm:ss").format(thoigianden.getDate());
            String thoiGianKhoiHanh = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(thoigiankhoihanh.getDate());
            String taiXe = taixe.getText();
            String phuXe = phuxe.getText();
            String slVe = slve_chuyenxe.getText();

            suachuyenxe.setValueAt(noiLenXe, i, 4);
            suachuyenxe.setValueAt(noiXuongXe, i, 5);
            suachuyenxe.setValueAt(thoiGianKhoiHanh, i, 6);
            suachuyenxe.setValueAt(thoiGianDen, i, 7);

            suachuyenxe.setValueAt(taiXe, i, 8);
            suachuyenxe.setValueAt(phuXe, i, 9);
            suachuyenxe.setValueAt(slVe, i, 9);
            boolean flag = true;
            if (noiLenXe.equals("")) {

                JOptionPane.showMessageDialog(this, "Vui lòng nhập nơi lên xe\n");
                flag = false;
            } else if (noiXuongXe.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập nơi xuống xe\n");
                flag = false;
            } else if (thoiGianDen.equals(""))
            {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập thời gian khởi hành\n");
                flag = false;
            }
            else if (taiXe.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tài xế\n");
                flag = false;
            } else if (phuXe.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập phụ xe");
                flag = false;
            }

            if (flag == true) {
                ChuyenXe db = new ChuyenXe();

                //Lay ket qua tu CSDL
                int countrecord = db.suaChuyenXe(maChuyenXe, maTuyenXe, maXe,
                        maNQL, noiLenXe, noiXuongXe, thoiGianKhoiHanh, thoiGianDen, taiXe, phuXe);

                if (countrecord > 0) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công!", "Thông báo",
                            JOptionPane.INFORMATION_MESSAGE, null);
                    hide();

                    Homepage_QuanLyChuyenXe classsuachuyenxe = new Homepage_QuanLyChuyenXe();
                    classsuachuyenxe.setVisible(true);
                    this.setVisible(false);

                } else {
                    JOptionPane.showMessageDialog(null, "Error");
                }
            }
        } else {
            if (dschuyenxe_chuyenxe.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Danh sách trống!",
                        "Lỗi dữ liệu ", JOptionPane.WARNING_MESSAGE, null);
//                    SuaChuyen classsuachuyenxe = new SuaChuyen();
//                    classsuachuyenxe.setVisible(true);
//                    this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chỉ chọn 1 tuyến xe cần sửa!",
                        "Lỗi thao tác", JOptionPane.WARNING_MESSAGE, null);
//                    SuaChuyen classsuachuyenxe = new SuaChuyen();
//                    classsuachuyenxe.setVisible(true);
//                    this.setVisible(false);
            }
        }
        }

    }//GEN-LAST:event_nutsua_chuyenxeActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Homepage_QuanLyChuyenXe quanlychuyenxe = new Homepage_QuanLyChuyenXe();
        quanlychuyenxe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void dangXuat_homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangXuat_homepageMouseClicked
        // TODO add your handling code here:
        Login_Form login = new Login_Form();
        login.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_dangXuat_homepageMouseClicked

    private void trangChu_homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trangChu_homepageMouseClicked
        // TODO add your handling code here:
        Homepage_NguoiQuanLy nguoiquanly = new Homepage_NguoiQuanLy();
        nguoiquanly.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_trangChu_homepageMouseClicked

    private void taixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taixeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taixeActionPerformed

    private void phuxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phuxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phuxeActionPerformed

    private void QuanLyTuyenXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyTuyenXeMouseClicked
        // TODO add your handling code here:
        Homepage_QuanLyTuyenXe quanlytuyenxe = new Homepage_QuanLyTuyenXe();
        quanlytuyenxe.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_QuanLyTuyenXeMouseClicked

    private void QuanLyChuyenXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyChuyenXeMouseClicked
        // TODO add your handling code here:
        Homepage_QuanLyChuyenXe quanlychuyenxe = new Homepage_QuanLyChuyenXe();
        quanlychuyenxe.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_QuanLyChuyenXeMouseClicked

    private void QuanLyXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyXeMouseClicked
        // TODO add your handling code here:
        Homepage_QuanLyXe quanlyxe = new Homepage_QuanLyXe();
        quanlyxe.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_QuanLyXeMouseClicked

    private void QuanLyLoaiXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyLoaiXeMouseClicked
        // TODO add your handling code here:
        Homepage_QuanLyLoaiXe quanlyloaixe = new Homepage_QuanLyLoaiXe();
        quanlyloaixe.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_QuanLyLoaiXeMouseClicked

    private void QuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyNhanVienMouseClicked
        // TODO add your handling code here:
        Homepage_QuanLyNhanVien quanlynhanvien = new Homepage_QuanLyNhanVien();
        quanlynhanvien.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_QuanLyNhanVienMouseClicked

    private void QuanLyGiaVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyGiaVeMouseClicked
        // TODO add your handling code here:
        Homepage_QuanLyGiaVe quanlygiave = new Homepage_QuanLyGiaVe();
        quanlygiave.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_QuanLyGiaVeMouseClicked

    private void cbbdiemdi_chuyenxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbdiemdi_chuyenxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbdiemdi_chuyenxeActionPerformed

    private void cbbdiemden_chuyenxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbdiemden_chuyenxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbdiemden_chuyenxeActionPerformed

    private void nuttim_chuyenxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuttim_chuyenxeActionPerformed

      if (ngay_chuyenxe.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày khởi hành!",
                    "Lỗi thao tác", JOptionPane.WARNING_MESSAGE, null);
//            ChonChuyen chonchuyen = new ChonChuyen();
//            chonchuyen.setVisible(true);
//            this.setVisible(false);

        } else {
            String diemdi = cbbdiemdi_chuyenxe.getSelectedItem().toString().trim();
            String diemden = cbbdiemden_chuyenxe.getSelectedItem().toString().trim();
            String ngaykhoihanh = new SimpleDateFormat("dd-MM-yyyy").format(ngay_chuyenxe.getDate());

            try {
                Class.forName("oracle.jdbc.OracleDriver");
                con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##TEST3", "Square1");
                pst = con.prepareStatement("SELECT c.id_chuyenxe, t.id_tuyenxe, c.id_xe, c.id_nql, c.diemdi, c.diemden, c.thoigiankh, c.thoigianden, c.taixe, c.phuxe, c.slvecon\n"
                        + "FROM TUYENXE T JOIN CHUYENXE C ON T.ID_TUYENXE = C.ID_TUYENXE\n"
                        + "WHERE T.DIEMDAU=? AND T.DIEMCUOI=? AND TO_CHAR(THOIGIANKH, 'DD-MM-YYYY') =?");

//                pst = con.prepareStatement("SELECT * from employee WHERE  userID = '" + userID + "'");
                pst.setString(1, diemdi);
                pst.setString(2, diemden);
                pst.setString(3, ngaykhoihanh);

                ResultSet rs = pst.executeQuery();

                ResultSetMetaData rsm = rs.getMetaData();
                int c;
                c = rsm.getColumnCount();

                DefaultTableModel Df = (DefaultTableModel) dschuyenxe_chuyenxe.getModel();
                Df.setRowCount(0);

                while (rs.next()) {
                    Vector v2 = new Vector();

                    for (int i = 1; i <= c; i++) {
                        v2.add(rs.getString("id_chuyenxe"));
                        v2.add(rs.getString("id_tuyenxe"));
                        v2.add(rs.getString("id_xe"));
                        v2.add(rs.getString("id_nql"));
                        v2.add(rs.getString("diemdi"));
                        v2.add(rs.getString("diemden"));

                        v2.add(String.valueOf(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(rs.getTimestamp("THOIGIANKH"))));
                        v2.add(String.valueOf(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(rs.getTimestamp("thoigianden"))));
                        v2.add(rs.getString("taixe"));
                        v2.add(rs.getString("phuxe"));
                        v2.add(rs.getInt("slvecon"));
                    }
                    Df.addRow(v2);
                }
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }//GEN-LAST:event_nuttim_chuyenxeActionPerformed

    private void dschuyenxe_chuyenxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dschuyenxe_chuyenxeMouseClicked
        // TODO add your handling code here:
        int selectedRow = dschuyenxe_chuyenxe.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) dschuyenxe_chuyenxe.getModel();
        machuyenxe_chuyenxe.setText(model.getValueAt(selectedRow, 0).toString());
        matuyenxe_chuyenxe.setText(model.getValueAt(selectedRow, 1).toString());
        maxe_chuyenxe.setText(model.getValueAt(selectedRow, 2).toString());
        manql_chuyenxe.setText(model.getValueAt(selectedRow, 3).toString());
        noilenxe.setText(model.getValueAt(selectedRow, 4).toString());
        noixuongxe.setText(model.getValueAt(selectedRow, 5).toString());
        try {
            Date ngaykhoihanh = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").parse((String) model.getValueAt(selectedRow, 6));
            Date ngayden = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").parse((String) model.getValueAt(selectedRow, 7));
            thoigiankhoihanh.setDate(ngaykhoihanh);
            thoigianden.setDate(ngayden);
        } catch (ParseException ex) {
            Logger.getLogger(SuaChuyen.class.getName()).log(Level.SEVERE, null, ex);
        }

        taixe.setText(model.getValueAt(selectedRow, 8).toString());
        phuxe.setText(model.getValueAt(selectedRow, 9).toString());
        slve_chuyenxe.setText(model.getValueAt(selectedRow, 10).toString());


    }//GEN-LAST:event_dschuyenxe_chuyenxeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaChuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaChuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaChuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaChuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaChuyen().setVisible(true);
            }
        });
    }

    public void fillTable() {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##TEST3", "Square1");
            Statement st = con.createStatement();
            String sql = "select * from CHUYENXE  ";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                String idchuyenxe = String.valueOf(rs.getInt("ID_CHUYENXE"));
                String idtuyenxe = String.valueOf(rs.getInt("ID_TUYENXE"));
                String idxe = String.valueOf(rs.getInt("ID_XE"));
                String idnql = String.valueOf(rs.getInt("ID_NQL"));
                String diemdi = rs.getString("DIEMDI");
                String diemden = rs.getString("DIEMDEN");

                String thoigiankhoihanh = String.valueOf(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(rs.getTimestamp("THOIGIANKH")));;

                String thoigianden = String.valueOf(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(rs.getTimestamp("THOIGIANDEN")));
                String taixe = String.valueOf(rs.getString("TAIXE"));
                String phuxe = String.valueOf(rs.getString("PHUXE"));
                String slve = String.valueOf(rs.getInt("SLVECON"));
                String tbData[] = {idchuyenxe, idtuyenxe, idxe, idnql, diemdi, diemden, thoigiankhoihanh, thoigianden, taixe, phuxe, slve};
                DefaultTableModel tblModel = (DefaultTableModel) dschuyenxe_chuyenxe.getModel();

                tblModel.addRow(tbData);
            }

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void loadcbbdiemdi() {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##TEST3", "Square1");
            PreparedStatement pst = con.prepareStatement("Select DISTINCT DIEMCUOI from TUYENXE where tinhtrang = 'Hoạt động'");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                cbbdiemdi_chuyenxe.addItem(rs.getString(1));

            }

        } catch (ClassNotFoundException e1) {
            e1.printStackTrace();
        } catch (SQLException e1) {
            e1.printStackTrace();
        }
    }

    void loadcbbdiemden() {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##TEST3", "Square1");
            PreparedStatement pst = con.prepareStatement("Select DISTINCT DIEMDAU from TUYENXE where tinhtrang = 'Hoạt động'");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                cbbdiemden_chuyenxe.addItem(rs.getString(1));

            }

        } catch (ClassNotFoundException e1) {
            e1.printStackTrace();
        } catch (SQLException e1) {
            e1.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbdiemden_chuyenxe;
    private javax.swing.JComboBox<String> cbbdiemdi_chuyenxe;
    private javax.swing.JPanel dangXuat_homepage;
    private javax.swing.JTable dschuyenxe_chuyenxe;
    private javax.swing.JPanel gioiThieu_homepage;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JSpinnerDateEditor jSpinnerDateEditor2;
    private javax.swing.JLabel machuyenxe_chuyenxe;
    private javax.swing.JLabel manql_chuyenxe;
    private javax.swing.JLabel matuyenxe_chuyenxe;
    private javax.swing.JLabel maxe_chuyenxe;
    private com.toedter.calendar.JDateChooser ngay_chuyenxe;
    private javax.swing.JTextField noilenxe;
    private javax.swing.JTextField noixuongxe;
    private javax.swing.JButton nutsua_chuyenxe;
    private javax.swing.JButton nuttim_chuyenxe;
    private javax.swing.JTextField phuxe;
    private javax.swing.JLabel slve_chuyenxe;
    private javax.swing.JTextField taixe;
    private com.toedter.calendar.JSpinnerDateEditor thoigianden;
    private com.toedter.calendar.JSpinnerDateEditor thoigiankhoihanh;
    private javax.swing.JPanel trangChu_homepage8;
    // End of variables declaration//GEN-END:variables
}
