
     
    CREATE TABLE "DB_XEKHACH"."CHUYENXE" 
   (	"ID" NUMBER(*,0), 
	"TTXE_ID" NUMBER(*,0), 
   "BENDI_ID" NUMBER(*,0),
   "BENDEN_ID" NUMBER(*,0),
   "THOIGIAN_KH" DATE,
   "THOIGIAN_DEN" DATE, 
   "TONGSOVE" NUMBER(*,0), 
   "NGUOIQUANLY_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

Insert into DB_XEKHACH.CHUYENXE (ID,TTXE_ID,BENDI_ID,BENDEN_ID,THOIGIAN_KH,THOIGIAN_DEN,TONGSOVE,NGUOIQUANLY_ID) values (401,1120, 10001, 10002,to_date('12-FEB-21 00:00:00','DD-MON-RR HH24:MI:SS'),to_date('16-FEB-21 00:00:00','DD-MON-RR HH24:MI:SS'),20,210  );  
Insert into DB_XEKHACH.CHUYENXE (ID,TTXE_ID,BENDI_ID,BENDEN_ID,THOIGIAN_KH,THOIGIAN_DEN,TONGSOVE,NGUOIQUANLY_ID) values (402,1115, 10001, 10002,to_date('13-FEB-22 00:00:00','DD-MON-RR HH24:MI:SS'),to_date('14-FEB-22 00:00:00','DD-MON-RR HH24:MI:SS'),40,208  ); 
Insert into DB_XEKHACH.CHUYENXE (ID,TTXE_ID,BENDI_ID,BENDEN_ID,THOIGIAN_KH,THOIGIAN_DEN,TONGSOVE,NGUOIQUANLY_ID) values (403,1110, 10001, 10002,to_date('14-FEB-22 00:00:00','DD-MON-RR HH24:MI:SS'),to_date('16-FEB-22 00:00:00','DD-MON-RR HH24:MI:SS'),34,206  ); 


--  Constraints for Table CHUYENXE
--------------------------------------------------------
  PROMPT Creating Primary Key on 'CHUYENXE'
  ALTER TABLE CHUYENXE
  ADD CONSTRAINT ID_CHUYENXE_PK PRIMARY KEY(ID)

--  Ref Constraints for Table CHUYENXE
--------------------------------------------------------
    PROMPT Creating Foreign Keys on 'CHUYENXE'
    ALTER TABLE CHUYENXE
    ADD CONSTRAINT TTXEID_CHUYENXE_FK
    FOREIGN KEY (TTXE_ID) REFERENCES TTXE(ID);   