--------------------------------------------------------
--  File created - T4-04-13-2022   
--------------------------------------------------------
--  DDL for Sequence DICHVUBOTRO_ID
--------------------------------------------------------

   CREATE SEQUENCE  "DB_XEKHACH"."DICHVUBOTRO_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4001 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------

--  DDL for Table DICHVUBOTRO
--------------------------------------------------------

CREATE TABLE "DB_XEKHACH"."DICHVUBOTRO" 
   (	"ID" NUMBER(*,0), 
	"NOIDUNGDV" VARCHAR2(100 BYTE), 
	"GIADV" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
REM INSERTING into DB_XEKHACH.DICHVUBOTRO
SET DEFINE OFF;
Insert into DB_XEKHACH.DICHVUBOTRO (ID,NOIDUNGDV,GIADV) values (4001,'10 kg',150000);
Insert into DB_XEKHACH.DICHVUBOTRO (ID,NOIDUNGDV,GIADV) values (4002,'15 kg',200000);
Insert into DB_XEKHACH.DICHVUBOTRO (ID,NOIDUNGDV,GIADV) values (4003,'20 kg',250000);
Insert into DB_XEKHACH.DICHVUBOTRO (ID,NOIDUNGDV,GIADV) values (4004,'25 kg',300000);
Insert into DB_XEKHACH.DICHVUBOTRO (ID,NOIDUNGDV,GIADV) values (4005,'10 kg',200000);
Insert into DB_XEKHACH.DICHVUBOTRO (ID,NOIDUNGDV,GIADV) values (4006,'15 kg',250000);
Insert into DB_XEKHACH.DICHVUBOTRO (ID,NOIDUNGDV,GIADV) values (4007,'20 kg',300000);
Insert into DB_XEKHACH.DICHVUBOTRO (ID,NOIDUNGDV,GIADV) values (4008,'25 kg',350000);

--------------------------------------------------------
--  DDL for Index DVBT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_XEKHACH"."DVBT_PK" ON "DB_XEKHACH"."DICHVUBOTRO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DICHVUBOTRO
--------------------------------------------------------

  ALTER TABLE "DB_XEKHACH"."DICHVUBOTRO" ADD CONSTRAINT "DV_PK" PRIMARY KEY ("ID")
  USING INDEX "DB_XEKHACH"."DVBT_PK"  ENABLE;
