  CREATE TABLE "DB_XEKHACH"."LOAIXE" 
   (	"ID" NUMBER(*,0), 
	"TENLOAIXE" VARCHAR2(50 BYTE), 
   "GIAVE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
Insert into DB_XEKHACH.LOAIXE (ID,TENLOAIXE,GIAVE) values (111,'Standard',250000 );   
Insert into DB_XEKHACH.LOAIXE (ID,TENLOAIXE,GIAVE) values (222,'Vip',300000 );   
Insert into DB_XEKHACH.LOAIXE (ID,TENLOAIXE,GIAVE) values (333,'Luxury',500000 );   

--  Constraints for Table LOAIXE
--------------------------------------------------------
  PROMPT Creating Primary Key on 'LOAIXE'
  ALTER TABLE LOAIXE
  ADD CONSTRAINT ID_LOAIXE_PK PRIMARY KEY(ID)
  
  