
  CREATE TABLE "DB_XEKHACH"."TTXE" 
   (	"ID" NUMBER(*,0), 
	"TENXE" VARCHAR2(50 BYTE), 
	"HANGSANXUAT" VARCHAR2(50 BYTE), 
	"TONGSOGHE" NUMBER(*,0), 
	"LOAIXE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

REM INSERTING into DB_XEKHACH.TTXE
SET DEFINE OFF;
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1101,'QWE','Hyundai',29,111);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1102,'QWR','Hyundai',29,111);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1103,'QWT','Hyundai',29,111);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1104,'QWY','Hyundai',29,111);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1105,'QWU','Hyundai',29,111);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1106,'TYU','Hyundai',29,111);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1107,'TYI','Toyota',35,222);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1108,'TYO','Toyota',35,222);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1109,'TYP','Toyota',35,222);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1110,'TYA','Toyota',35,222);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1111,'TYS','Toyota',35,222);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1112,'TYD','Toyota',35,222);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1113,'WER','Suzuki',45,333);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1114,'WET','Suzuki',45,333);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1115,'WEY','Suzuki',45,333);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1116,'WEU','Suzuki',45,333);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1117,'WEI','Suzuki',45,333);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1118,'WEO','Suzuki',45,333);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1119,'WEP','Suzuki',45,333);
Insert into DB_XEKHACH.TTXE (ID,TENXE,HANGSANXUAT,TONGSOGHE,LOAIXE_ID) values (1120,'WEA','Suzuki',45,333);

--  Constraints for Table TTXE
--------------------------------------------------------
  PROMPT Creating Primary Key on 'TTXE'
  ALTER TABLE TTXE
  ADD CONSTRAINT ID_TTXE_PK PRIMARY KEY(ID)

--  Ref Constraints for Table LOAIXE
--------------------------------------------------------
    PROMPT Creating Foreign Keys on 'LOAIXE'
    ALTER TABLE LOAIXE
    ADD CONSTRAINT LOAIXEID_TTXE_FK
    FOREIGN KEY (LOAIXE_ID) REFERENCES LOAIXE(ID);  