  CREATE TABLE "DB_XEKHACH"."VEXE" 
   (	"ID" NUMBER(*,0), 
	"CHUYENXE_ID"NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
   Insert into DB_XEKHACH.VEXE (ID,CHUYENXE_ID) values (9000,403 );   
   Insert into DB_XEKHACH.VEXE (ID,CHUYENXE_ID) values (9001,402 );   
   Insert into DB_XEKHACH.VEXE (ID,CHUYENXE_ID) values (9002,401 );   
  
  --  Constraints for Table VEXE
--------------------------------------------------------
  PROMPT Creating Primary Key on 'VEXE'
  ALTER TABLE VEXE
  ADD CONSTRAINT ID_VEXE_PK PRIMARY KEY(ID)
  
  --  Ref Constraints for Table VEXE
--------------------------------------------------------
    PROMPT Creating Foreign Keys on 'VEXE'
    ALTER TABLE VEXE
    ADD CONSTRAINT CHUYENXEID_VEXE_FK
    FOREIGN KEY (CHUYENXE_ID) REFERENCES CHUYENXE(ID); 
