/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.QuanLy.NhanVien;

import Process.QuanLy.TuyenXe.NhanVien;
import View.Home.Login_Form;
import View.QuanLy.ChuyenXe.Homepage_QuanLyChuyenXe;
import View.QuanLy.GiaVe.Homepage_QuanLyGiaVe;
import View.QuanLy.Homepage_NguoiQuanLy;
import View.QuanLy.LoaiXe.Homepage_QuanLyLoaiXe;
import View.QuanLy.TuyenXe.Homepage_QuanLyTuyenXe;
import View.QuanLy.Xe.Homepage_QuanLyXe;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.Normalizer;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author duyta
 */
public class SuaNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form Homepage_NguoiQuanLy
     */
    public SuaNhanVien() {
        initComponents();
        fillTable();
        loadcbb();
    }
    Connection con;
    PreparedStatement pst;

    public void CloseFrame() {
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gioitinh_nhanvien = new javax.swing.ButtonGroup();
        gioiThieu_homepage = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel51 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        nutsua_nhanvien = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        danhsachnhanvien_nhanvien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        nuttimkiem_quanlynhanvien = new javax.swing.JButton();
        otimkiemnhanvien = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        quaylai_quanlytuyenxe = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        manhanvien_nhanvien = new javax.swing.JLabel();
        ngayvaolam_nhanvien = new com.toedter.calendar.JDateChooser();
        ngaysinh_nhanvien = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        manqlmoi_nhanvien1 = new javax.swing.JComboBox<>();
        maquanlycu_nhanvien = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sdt_nhanvien = new javax.swing.JTextField();
        email_nhanvien = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nam_nhanvien = new javax.swing.JRadioButton();
        nu_nhanvien = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        hoten_nhanvien = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tendangnhap_nhanvien = new javax.swing.JLabel();
        A = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        trangChu_homepage8 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        dangXuat_homepage = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gioiThieu_homepage.setBackground(new java.awt.Color(251, 250, 238));
        gioiThieu_homepage.setPreferredSize(new java.awt.Dimension(680, 500));

        jSeparator1.setForeground(new java.awt.Color(205, 247, 247));

        jLabel51.setFont(new java.awt.Font("Lora Medium", 2, 14)); // NOI18N
        jLabel51.setText("Sự hài lòng của quý khách");

        jLabel18.setFont(new java.awt.Font("Lora Medium", 2, 14)); // NOI18N
        jLabel18.setText("là minh chứng cho chất lượng dịch vụ của hãng xe Thanh Xuân");

        jLabel54.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_heart_20px_3.png"))); // NOI18N
        jLabel54.setText("Mời sửa nhân viên!");

        jSeparator3.setForeground(new java.awt.Color(205, 247, 247));

        jPanel6.setBackground(new java.awt.Color(251, 250, 238));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/QuanLy/Icon/QuanLyTuyenXe/icons8_edit_30px_3.png"))); // NOI18N

        nutsua_nhanvien.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        nutsua_nhanvien.setText("Sửa");
        nutsua_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutsua_nhanvienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nutsua_nhanvien)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nutsua_nhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        danhsachnhanvien_nhanvien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));
        danhsachnhanvien_nhanvien.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        danhsachnhanvien_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Mã người quản lý", "Tên đăng nhập", "Tên nhân viên", "Giới tính", "Ngày sinh", "Ngày vào làm", "Số điện thoại", "Email"
            }
        ));
        danhsachnhanvien_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                danhsachnhanvien_nhanvienMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(danhsachnhanvien_nhanvien);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/QuanLy/Icon/QuanLyTuyenXe/icons8_search_30px_3.png"))); // NOI18N

        nuttimkiem_quanlynhanvien.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        nuttimkiem_quanlynhanvien.setText("Tìm kiếm");
        nuttimkiem_quanlynhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuttimkiem_quanlynhanvienActionPerformed(evt);
            }
        });

        otimkiemnhanvien.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        otimkiemnhanvien.setToolTipText("");
        otimkiemnhanvien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));
        otimkiemnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otimkiemnhanvienActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(251, 250, 238));

        quaylai_quanlytuyenxe.setFont(new java.awt.Font("Lora SemiBold", 0, 14)); // NOI18N
        quaylai_quanlytuyenxe.setText("Quay lại");
        quaylai_quanlytuyenxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaylai_quanlytuyenxeActionPerformed(evt);
            }
        });

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/QuanLy/Icon/QuanLyTuyenXe/icons8_return_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quaylai_quanlytuyenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quaylai_quanlytuyenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(27, 27, 27))
        );

        jPanel2.setBackground(new java.awt.Color(251, 250, 238));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));

        jLabel5.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel5.setText("Mã người quản lý hiện tại");

        jLabel8.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel8.setText("Ngày vào làm");

        jLabel9.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel9.setText("Ngày sinh");

        jLabel12.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel12.setText("Mã nhân viên");

        manhanvien_nhanvien.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        manhanvien_nhanvien.setText("Mã nhân viên");

        ngayvaolam_nhanvien.setDateFormatString("dd/MM/yyyy");

        ngaysinh_nhanvien.setDateFormatString("dd/MM/yyyy");

        jLabel10.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel10.setText("Mã người quản lý mới");

        manqlmoi_nhanvien1.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N

        maquanlycu_nhanvien.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        maquanlycu_nhanvien.setText("Mã người quản lý");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ngayvaolam_nhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(ngaysinh_nhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manqlmoi_nhanvien1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maquanlycu_nhanvien)
                    .addComponent(manhanvien_nhanvien))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(manhanvien_nhanvien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(maquanlycu_nhanvien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manqlmoi_nhanvien1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(ngayvaolam_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(ngaysinh_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(251, 250, 238));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 247, 247)));

        jLabel6.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel6.setText("Số điện thoại");

        jLabel7.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel7.setText("Email");

        sdt_nhanvien.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        sdt_nhanvien.setToolTipText("");

        email_nhanvien.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        email_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_nhanvienActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel13.setText("Giới tính");

        gioitinh_nhanvien.add(nam_nhanvien);
        nam_nhanvien.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        nam_nhanvien.setText("Nam ");
        nam_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nam_nhanvienActionPerformed(evt);
            }
        });

        gioitinh_nhanvien.add(nu_nhanvien);
        nu_nhanvien.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        nu_nhanvien.setText("Nữ");

        jLabel16.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel16.setText("Họ và tên");

        hoten_nhanvien.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        hoten_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoten_nhanvienActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        jLabel17.setText("Tên đăng nhập");

        tendangnhap_nhanvien.setFont(new java.awt.Font("Lora", 0, 12)); // NOI18N
        tendangnhap_nhanvien.setText("Tên đăng nhập");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sdt_nhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(email_nhanvien, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tendangnhap_nhanvien)
                                .addGap(46, 46, 46))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hoten_nhanvien)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(nam_nhanvien)
                                    .addGap(31, 31, 31)
                                    .addComponent(nu_nhanvien)
                                    .addContainerGap()))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tendangnhap_nhanvien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoten_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nam_nhanvien)
                    .addComponent(nu_nhanvien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sdt_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(email_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout gioiThieu_homepageLayout = new javax.swing.GroupLayout(gioiThieu_homepage);
        gioiThieu_homepage.setLayout(gioiThieu_homepageLayout);
        gioiThieu_homepageLayout.setHorizontalGroup(
            gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel54))
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(jLabel51)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(otimkiemnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nuttimkiem_quanlynhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(764, 764, 764)))
                .addContainerGap())
            .addGroup(gioiThieu_homepageLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gioiThieu_homepageLayout.setVerticalGroup(
            gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gioiThieu_homepageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nuttimkiem_quanlynhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gioiThieu_homepageLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(otimkiemnhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(gioiThieu_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        A.setBackground(new java.awt.Color(205, 247, 247));
        A.setPreferredSize(new java.awt.Dimension(220, 500));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/HÃNG XE KHÁCH (200 × 200 px).png"))); // NOI18N

        trangChu_homepage8.setBackground(new java.awt.Color(251, 250, 238));
        trangChu_homepage8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trangChu_homepage8trangChu_homepageMouseClicked(evt);
            }
        });

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_home_page_20px_1.png"))); // NOI18N

        jLabel53.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel53.setText("Trang chủ");

        javax.swing.GroupLayout trangChu_homepage8Layout = new javax.swing.GroupLayout(trangChu_homepage8);
        trangChu_homepage8.setLayout(trangChu_homepage8Layout);
        trangChu_homepage8Layout.setHorizontalGroup(
            trangChu_homepage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChu_homepage8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52)
                .addGap(30, 30, 30)
                .addComponent(jLabel53)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trangChu_homepage8Layout.setVerticalGroup(
            trangChu_homepage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChu_homepage8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(trangChu_homepage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(251, 250, 238));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16QuanLyTuyenXeMouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_map_pinpoint_20px_1.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel21.setText("Quản lý tuyến xe");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(30, 30, 30)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(251, 250, 238));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17QuanLyChuyenXeMouseClicked(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_windows_calendar_20px.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel23.setText("Quản lý chuyến xe");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(30, 30, 30)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(251, 250, 238));
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18QuanLyXeMouseClicked(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_Shuttle_bus_20px.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel25.setText("Quản lý xe");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(30, 30, 30)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(251, 250, 238));
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel19QuanLyLoaiXeMouseClicked(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_public_transportation_20px_1.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel27.setText("Quản lý loại xe");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(30, 30, 30)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel21.setBackground(new java.awt.Color(153, 153, 255));
        jPanel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel21QuanLyNhanVienMouseClicked(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_management_20px_1.png"))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel31.setText("Quản lý nhân viên");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(30, 30, 30)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel22.setBackground(new java.awt.Color(251, 250, 238));
        jPanel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel22QuanLyGiaVeMouseClicked(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_ticket_20px_1.png"))); // NOI18N

        jLabel33.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel33.setText("Quản lý giá vé");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(30, 30, 30)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dangXuat_homepage.setBackground(new java.awt.Color(251, 250, 238));
        dangXuat_homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangXuat_homepageMouseClicked(evt);
            }
        });

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icon/icons8_Logout_20px_3.png"))); // NOI18N

        jLabel35.setFont(new java.awt.Font("Lora SemiBold", 1, 12)); // NOI18N
        jLabel35.setText("Đăng xuất");

        javax.swing.GroupLayout dangXuat_homepageLayout = new javax.swing.GroupLayout(dangXuat_homepage);
        dangXuat_homepage.setLayout(dangXuat_homepageLayout);
        dangXuat_homepageLayout.setHorizontalGroup(
            dangXuat_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangXuat_homepageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(30, 30, 30)
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dangXuat_homepageLayout.setVerticalGroup(
            dangXuat_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangXuat_homepageLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(dangXuat_homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ALayout = new javax.swing.GroupLayout(A);
        A.setLayout(ALayout);
        ALayout.setHorizontalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ALayout.createSequentialGroup()
                        .addGroup(ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dangXuat_homepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trangChu_homepage8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11))
                    .addGroup(ALayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        ALayout.setVerticalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(trangChu_homepage8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dangXuat_homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gioiThieu_homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gioiThieu_homepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuttimkiem_quanlynhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuttimkiem_quanlynhanvienActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) danhsachnhanvien_nhanvien.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        danhsachnhanvien_nhanvien.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(otimkiemnhanvien.getText().trim()));
    }//GEN-LAST:event_nuttimkiem_quanlynhanvienActionPerformed

    private void otimkiemnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otimkiemnhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otimkiemnhanvienActionPerformed

    private void quaylai_quanlytuyenxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaylai_quanlytuyenxeActionPerformed
        // TODO add your handling code here:
        Homepage_QuanLyNhanVien quanly = new Homepage_QuanLyNhanVien();
        quanly.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_quaylai_quanlytuyenxeActionPerformed

    private void email_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_nhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_nhanvienActionPerformed

    private void nam_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nam_nhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nam_nhanvienActionPerformed

    private void hoten_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoten_nhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoten_nhanvienActionPerformed

    private void danhsachnhanvien_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_danhsachnhanvien_nhanvienMouseClicked
        // TODO add your handling code here:
        int selectedRow = danhsachnhanvien_nhanvien.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) danhsachnhanvien_nhanvien.getModel();
        manhanvien_nhanvien.setText(model.getValueAt(selectedRow, 0).toString());
        maquanlycu_nhanvien.setText(model.getValueAt(selectedRow, 1).toString());
        tendangnhap_nhanvien.setText(model.getValueAt(selectedRow, 2).toString());
        hoten_nhanvien.setText(model.getValueAt(selectedRow, 3).toString());
        if (model.getValueAt(selectedRow, 4).toString().equals("Nam")) {
            nam_nhanvien.setSelected(true);
        } else {
            nu_nhanvien.setSelected(true);
        }

        try {
            Date datengaysinh = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRow, 5));
            Date datengayvaolam = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRow, 6));
            ngayvaolam_nhanvien.setDate(datengayvaolam);
            ngaysinh_nhanvien.setDate(datengaysinh);
        } catch (ParseException ex) {
            Logger.getLogger(SuaNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

//        ngayvaolam_nhanvien.setDate(to_date(model.getValueAt(selectedRow, 5),'dd-MM-yyyy'));
//        ngayvaolam_nhanvien.setDate(SimpleDateFormat("dd-MM-yyyy").format(model.getValueAt(selectedRow, 5).getDate()));
        sdt_nhanvien.setText(model.getValueAt(selectedRow, 7).toString());
        email_nhanvien.setText(model.getValueAt(selectedRow, 8).toString());

    }//GEN-LAST:event_danhsachnhanvien_nhanvienMouseClicked

    private void nutsua_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutsua_nhanvienActionPerformed
        // TODO add your handling code here:
        DefaultTableModel suanhanvien = (DefaultTableModel) danhsachnhanvien_nhanvien.getModel();
        int i = danhsachnhanvien_nhanvien.getSelectedRow();

        if (danhsachnhanvien_nhanvien.getSelectedRowCount() == 1) {
            String iD = manhanvien_nhanvien.getText();
            String maQuanLy = manqlmoi_nhanvien1.getSelectedItem().toString().trim();

            String ten = hoten_nhanvien.getText();
            nam_nhanvien.setActionCommand("Nam");
            nu_nhanvien.setActionCommand("Nữ");
            String gioiTinh = gioitinh_nhanvien.getSelection().getActionCommand();
            String ngaySinh = new SimpleDateFormat("dd-MMM-yyyy").format(ngaysinh_nhanvien.getDate());
            String ngayVaoLam = new SimpleDateFormat("dd-MMM-yyyy").format(ngayvaolam_nhanvien.getDate());
            String sDT = sdt_nhanvien.getText();
            String eMail = email_nhanvien.getText();

            suanhanvien.setValueAt(iD, i, 1);
            suanhanvien.setValueAt(maQuanLy, i, 2);
            suanhanvien.setValueAt(ten, i, 3);
            suanhanvien.setValueAt(gioiTinh, i, 4);
            suanhanvien.setValueAt(ngaySinh, i, 5);
            suanhanvien.setValueAt(ngayVaoLam, i, 6);
            suanhanvien.setValueAt(sDT, i, 7);
            suanhanvien.setValueAt(eMail, i, 8);
            boolean flag = true;
            if (ten.equals("")) {

                JOptionPane.showMessageDialog(this, "Vui lòng nhập tên hành khách\n");
                flag = false;
            } else if (sDT.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại\n");
                flag = false;
            } else if (eMail.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Email");
                flag = false;
            } else if (ngayvaolam_nhanvien.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Vui lòng ngày vào làm của nhân viên");
                flag = false;
            } else if (ngaysinh_nhanvien.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập ngày sinh của nhân viên");
                flag = false;
            }
//            if (flag == true) {
//                String temp = Normalizer.normalize(ten, Normalizer.Form.NFD);
//                    Pattern pattern = Pattern.compile("\\p{InCombiningDiacriticalMarks}+");
//                  // return pattern.matcher(temp).replaceAll("");
////                   flag = false;
////                    String tennv = "^[a-z Ạ-ỹ A-Z]$";
////                    boolean flag4 = ten.matches(tennv);
//                    if (flag4 == false) {
//                        JOptionPane.showMessageDialog(this, "Tên nhân viên không hợp lệ");
//                        flag = false;
//                    }
//                }
                
                if (flag == true) {
                    int result = ngaySinh.compareTo(ngayVaoLam);
                    if (result == 0) {
                        JOptionPane.showMessageDialog(null, "Nhân viên không thể sinh trong ngày vào làm  :)");
                        flag = false;
                    } else if (result > 0) {
                        JOptionPane.showMessageDialog(null, "Nhân viên không thể sinh sau ngày vào làm  :)");
                        flag = false;
                    } else if (result < 0) {
//                        JOptionPane.showMessageDialog(null, "Nhân viên không thể sinh sau ngày vào làm :))");
//                        flag = false;
                    } else {
                        System.out.println("How to get here?");
                    }
                }
                if (flag == true) {
                    DateFormat simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy");
                    try {
                        Date ngaysinh = simpleDateFormat.parse(ngaySinh);
                        Date ngayvaolam = simpleDateFormat.parse(ngayVaoLam);
                        long getDiff = (ngaysinh.getTime() - ngayvaolam.getTime());
                        if (getDiff / 12 < 18) {
                            JOptionPane.showMessageDialog(null, "Nhân viên chưa đủ 18 tuổi  :)");
                            flag = false;
                        }
                    } catch (ParseException ex) {
                        Logger.getLogger(ThemNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    int result = ngaySinh.compareTo(ngayVaoLam);
                    if (result == 0) {
                        JOptionPane.showMessageDialog(null, "Nhân viên không thể sinh trong ngày vào làm  :)");
                        flag = false;
                    } else if (result > 0) {
                        JOptionPane.showMessageDialog(null, "Nhân viên không thể sinh sau ngày vào làm  :)");
                        flag = false;
                    } else if (result < 0) {
//                        JOptionPane.showMessageDialog(null, "Nhân viên không thể sinh sau ngày vào làm :))");
//                        flag = false;
                    } else {
                        System.out.println("How to get here?");
                    }
                }
            if (flag == true) {
                String reg = "^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$";
                boolean flag2 = sDT.matches(reg);
                if (flag2 == false) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại không đúng hoặc không hợp lệ");
                    flag = false;
                }
            }
            if (flag == true) {
                String emailPattern = "\\w+@\\w+[.]\\w+([.]\\w+)?";
                boolean flag4 = eMail.matches(emailPattern);
                if (flag4 == false) {
                    JOptionPane.showMessageDialog(this, "Email không hợp lệ");
                    flag = false;
                }
            }
            if (flag == true) {
                NhanVien db = new NhanVien();

                //Lay ket qua tu CSDL
                int sodongsua = db.suaNhanVien(iD, maQuanLy, ten,
                        gioiTinh, ngaySinh, ngayVaoLam, sDT, eMail);

                System.out.println(sodongsua);
                if (sodongsua > 0) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công!", "Thông báo",
                            JOptionPane.INFORMATION_MESSAGE, null);
                    hide();

                    Homepage_QuanLyNhanVien homepage = new Homepage_QuanLyNhanVien();
                    homepage.setVisible(true);
                    this.setVisible(false);

                } else {
                    JOptionPane.showMessageDialog(null, "Error");
                }
            }
        } else {
            if (danhsachnhanvien_nhanvien.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Bảng không có dữ liệu!",
                        "Lỗi", JOptionPane.WARNING_MESSAGE, null);
                Homepage_QuanLyNhanVien homepage = new Homepage_QuanLyNhanVien();
                homepage.setVisible(true);
                this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chỉ chọn 1 nhân viên cần sửa!",
                        "Lỗi thao tác", JOptionPane.WARNING_MESSAGE, null);
                SuaNhanVien homepage = new SuaNhanVien();
                homepage.setVisible(true);
                this.setVisible(false);

            }
        }
    }//GEN-LAST:event_nutsua_nhanvienActionPerformed

    private void trangChu_homepage8trangChu_homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trangChu_homepage8trangChu_homepageMouseClicked
        // TODO add your handling code here:
        Homepage_NguoiQuanLy nguoiquanly = new Homepage_NguoiQuanLy();
        nguoiquanly.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_trangChu_homepage8trangChu_homepageMouseClicked

    private void jPanel16QuanLyTuyenXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16QuanLyTuyenXeMouseClicked
        // TODO add your handling code here:
        Homepage_QuanLyTuyenXe quanlytuyenxe = new Homepage_QuanLyTuyenXe();
        quanlytuyenxe.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jPanel16QuanLyTuyenXeMouseClicked

    private void jPanel17QuanLyChuyenXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17QuanLyChuyenXeMouseClicked
        // TODO add your handling code here:
        Homepage_QuanLyChuyenXe quanlychuyenxe = new Homepage_QuanLyChuyenXe();
        quanlychuyenxe.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jPanel17QuanLyChuyenXeMouseClicked

    private void jPanel18QuanLyXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18QuanLyXeMouseClicked
        // TODO add your handling code here:
        Homepage_QuanLyXe quanlyxe = new Homepage_QuanLyXe();
        quanlyxe.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jPanel18QuanLyXeMouseClicked

    private void jPanel19QuanLyLoaiXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19QuanLyLoaiXeMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        Homepage_QuanLyLoaiXe quanlyloaixe = new Homepage_QuanLyLoaiXe();
        quanlyloaixe.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jPanel19QuanLyLoaiXeMouseClicked

    private void jPanel21QuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel21QuanLyNhanVienMouseClicked
        // TODO add your handling code here:
        Homepage_QuanLyNhanVien quanlynhanvien = new Homepage_QuanLyNhanVien();
        quanlynhanvien.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jPanel21QuanLyNhanVienMouseClicked

    private void jPanel22QuanLyGiaVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel22QuanLyGiaVeMouseClicked
        // TODO add your handling code here:
        Homepage_QuanLyGiaVe quanlygiave = new Homepage_QuanLyGiaVe();
        quanlygiave.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jPanel22QuanLyGiaVeMouseClicked

    private void dangXuat_homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangXuat_homepageMouseClicked
        // TODO add your handling code here:
        Login_Form login = new Login_Form();
        login.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_dangXuat_homepageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaNhanVien().setVisible(true);
            }
        });
    }

    public void fillTable() {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##TEST3", "Square1");
            Statement st = con.createStatement();
            String sql = "select * from NHANVIEN WHERE tinhtrang = 'Hoạt động' ";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                String maNhanVien = rs.getString("ID_NHANVIEN");
                String maNQL = rs.getString("ID_NQL");
                String tenDangNhap = rs.getString("TENDANGNHAP");
                String tenNhanVien = rs.getString("TENNV");
                String gioiTinh = rs.getString("GIOITINH");
                String ngaySinh = String.valueOf(new SimpleDateFormat("dd-MM-yyyy").format(rs.getTimestamp("NGAYSINH")));
                String ngayVaoLam = String.valueOf(new SimpleDateFormat("dd-MM-yyyy").format(rs.getTimestamp("NGAYVAOLAM")));
                String sDT = rs.getString("SDT");
                String eMail = rs.getString("EMAIL");
                String tbData[] = {maNhanVien, maNQL, tenDangNhap, tenNhanVien, gioiTinh, ngaySinh, ngayVaoLam, sDT, eMail};
                DefaultTableModel tblModel = (DefaultTableModel) danhsachnhanvien_nhanvien.getModel();

                tblModel.addRow(tbData);
            }

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void loadcbb() {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##TEST3", "Square1");
            PreparedStatement pst = con.prepareStatement("Select DISTINCT ID_NQL from NGUOIQUANLY");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                manqlmoi_nhanvien1.addItem(rs.getString(1));

            }

        } catch (ClassNotFoundException e1) {
            e1.printStackTrace();
        } catch (SQLException e1) {
            e1.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A;
    private javax.swing.JPanel dangXuat_homepage;
    private javax.swing.JTable danhsachnhanvien_nhanvien;
    private javax.swing.JTextField email_nhanvien;
    private javax.swing.JPanel gioiThieu_homepage;
    private javax.swing.ButtonGroup gioitinh_nhanvien;
    private javax.swing.JTextField hoten_nhanvien;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel manhanvien_nhanvien;
    private javax.swing.JComboBox<String> manqlmoi_nhanvien1;
    private javax.swing.JLabel maquanlycu_nhanvien;
    private javax.swing.JRadioButton nam_nhanvien;
    private com.toedter.calendar.JDateChooser ngaysinh_nhanvien;
    private com.toedter.calendar.JDateChooser ngayvaolam_nhanvien;
    private javax.swing.JRadioButton nu_nhanvien;
    private javax.swing.JButton nutsua_nhanvien;
    private javax.swing.JButton nuttimkiem_quanlynhanvien;
    private javax.swing.JTextField otimkiemnhanvien;
    private javax.swing.JButton quaylai_quanlytuyenxe;
    private javax.swing.JTextField sdt_nhanvien;
    private javax.swing.JLabel tendangnhap_nhanvien;
    private javax.swing.JPanel trangChu_homepage8;
    // End of variables declaration//GEN-END:variables
}
